### ISSUE TITLE
Object casted array construction causes Squiz.Arrays.ArrayDeclaration.ValueNoNewline errors

### ISSUE THREAD

**Issue by adaamz** [squizlabs/PHP_CodeSniffer#3141] opened 2020-10-13 09:05 UTC
Hi,
I'm not sure if this is bug or desired feature - if feature then how should I reformat my code?

**Describe the bug**
When I use (object) casting for array in array declaration I get these errors. When I remove object csating, there are no errors.

**Code sample**
```php
<?php
$list = (object)[
    "nodes" => [
        (object)[
            "id" => "asdfg",
            "nodeType" => "StartNode",
            "parameters" => (object)[],
        ],
        (object)[
            "id" => "fnjdkngjkfd",
            "nodeType" => "EndNode",
            "parameters" => (object)[],
        ],
    ],
];
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php --standard=ruleset.xml --extensions=php --encoding=utf-8 --tab-width=4 -sp ./test.php`
3. See error messages displayed
```
 4 | ERROR | [x] The first value in a multi-value array must be on a new line (Squiz.Arrays.ArrayDeclaration.ValueNoNewline)
 9 | ERROR | [x] Each value in a multi-line array must be on a new line (Squiz.Arrays.ArrayDeclaration.ValueNoNewline)
```

**Expected behavior**
No errors.

**Versions:**
 - OS: Windows 10
 - PHP: 7.3.7
 - PHPCS: 3.5.6
 - Standard: [slevomat/coding-standard](https://github.com/slevomat/coding-standard/blob/6.4.1/SlevomatCodingStandard/ruleset.xml)

**Comment by gsherwood** [comment] 2020-10-13 21:30
This is a duplicate of #3059, which has been fixed in master and will be released in 3.5.7. Thanks for the detailed report.

**Closed by gsherwood** 2020-10-13 21:30 UTC
