### ISSUE TITLE
no errors were fixed

### ISSUE THREAD

**Issue by justinblayney** [squizlabs/PHP_CodeSniffer#2573] opened 2019-08-01 20:05 UTC
Hello,
I am brand new to this, I just tried running my first fix and I get this error. I have not done anything except run the command in SSH, my web host installed the PHPCS for me

Processing artist.php [PHP => 1509 tokens in 286 lines]... DONE in 124ms (98 fixable violations)
        => Fixing file: 1/98 violations remaining [made 50 passes]... ERROR in 5.13 secs
No fixable errors were found
Time: 5.4 secs; Memory: 16Mb

My code is pretty old, I am still using mysql connections, which is the reason i am trying to upgrade. I plan on bringing everything up to 7.3 and was hoping phpcbf would do much of the heavy lifting for me

**Comment by jrfnl** [comment] 2019-08-02 00:41
@justinblayney Regarding the fixer not giving you the expected results: there's not much anyone can do without a code sample to look at to see what's going on. We'd also need to know the standard/custom ruleset you are using.

Secondly, PHPCS itself does not contain sniffs to upgrade your code to work on higher PHP versions. It can _clean up_ your code to make it comply with a standard like PSR-2 or PSR-12, but it will not fix things which are outside the realm of _code style_.

The external PHPCS standard [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) will also not auto-fix these, but can at least detect a lot of the issues which will need your attention.

Other than that, [Rector](https://github.com/rectorphp/rector) may be abe to get you closer to what you are looking for.

**Comment by justinblayney** [comment] 2019-08-02 01:32
Hello,
I figured the upgrade part, that would have made my life too easy..

but I did run phpcbf, i thought that was supposed to fix the 98 errors it detected, most of which were spacing, tabs and line exceed issues.   

Is there something I need to add to me php page for it to test against?  I cant find any documentation other than phpcs lists the errors and phpcbf will fix those errors

@jrfnl do you actually want to see my php code? or just what I ran in ssh ?

**Comment by jrfnl** [comment] 2019-08-04 23:31
@justinblayney Well, having something to test with to see if someone can reproduce the issue would be helpful....

As I said above:
> there's not much anyone can do without a code sample to look at to see what's going on. We'd also need to know the standard/custom ruleset you are using.

**Comment by justinblayney** [comment] 2019-08-06 15:12
Hello,
This is  the code that caused all the errors but none were fixed 

`<?php require_once('Connections/mine.php'); ?>
<?php include("includes/access_admin.php"); ?>
<?php

function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}



/*

if (!isset($_SESSION)) {
  session_start();

}
$MM_UserID = $_SESSION['MM_UserID'];
 
echo $MM_UserID;

$insertSQL = sprintf("INSERT INTO admin_tracking (admin_tracking_user) VALUES (%s)",
                         GetSQLValueString($MM_UserID, "int"));

mysql_select_db($database_mine, $mine);
  $Result1 = mysql_query($insertSQL, $mine) or die(header("Location:reporting_page.php?the_error=".mysql_error()."&the_page=".basename($_SERVER["PHP_SELF"]).""));
	*/





$message = $_GET['message'];

$editFormAction = $_SERVER['PHP_SELF'];
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}



if ((isset($_POST["MM_insert"])) && ($_POST["MM_insert"] == "form1")) {
  $insertSQL = sprintf("INSERT INTO artist (artist_name) VALUES (%s)",
                       GetSQLValueString($_POST['artist_name'], "text"));

  mysql_select_db($database_mine, $mine);
  $Result1 = mysql_query($insertSQL, $mine) or die(header("Location:reporting_page.php?the_error=".mysql_error()."&the_page=".basename($_SERVER["PHP_SELF"]).""));

  $insertGoTo = "artist.php?message=<h5>Artist Added</h5>";
  header(sprintf("Location: %s", $insertGoTo));
}




if ((isset($_POST["MM_update"])) && ($_POST["MM_update"] == "form2")) {
  $updateSQL = sprintf("UPDATE artist SET artist_name=%s,  artist_active=%s WHERE artist_id=%s",
                       GetSQLValueString($_POST['artist_name'], "text"),
					   GetSQLValueString(isset($_POST['artist_active']) ? "true" : "", "defined","1","0"),
					   
                       GetSQLValueString($_POST['artist_id'], "int"));

  mysql_select_db($database_mine, $mine);
  $Result1 = mysql_query($updateSQL, $mine) or die(header("Location:reporting_page.php?the_error=".mysql_error()."&the_page=".basename($_SERVER["PHP_SELF"]).""));

  $updateGoTo = "artist.php?message=<h5>Artist Updated</h5>";
  header(sprintf("Location: %s", $updateGoTo));
}



///  -- DELETE USERS START --- ///


if ((isset($_POST["formDelete"])) && ($_POST["formDelete"] == "Delete")) {
 $deleteSQL = sprintf("DELETE FROM artist WHERE artist_id=%s",
                       GetSQLValueString($_POST['artist_id'], "int"));

  mysql_select_db($database_mine, $mine);
  $Result1 = mysql_query($deleteSQL, $mine) or die(header("Location:reporting_page.php?the_error=".mysql_error()."&the_page=".basename($_SERVER["PHP_SELF"]).""));

  $updateGoTo = "artist.php";
  header(sprintf("Location: %s", $updateGoTo));
}
///  -- DELETE USERS STARTD --- ///






mysql_select_db($database_mine, $mine);
$query_Recordset1 = "SELECT * FROM artist ORDER BY artist_name ASC";
$Recordset1 = mysql_query($query_Recordset1, $mine) or die(header("Location:reporting_page.php?the_error=".mysql_error()."&the_page=".basename($_SERVER["PHP_SELF"]).""));
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);
?>
<?php include("includes/header.php"); ?>
 `

**Comment by jrfnl** [comment] 2019-08-06 15:31
@justinblayney Can you please [wrap the code in backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) so it becomes readable ? And what ruleset did you run against this code ? Ahat was the command you used ?

**Comment by gsherwood** [comment] 2019-08-06 23:09
I've fixed the code block in the comment above and tried running PHPCS over the code. None of the included standards generate 98 errors for the code, so I'm assuming you are running a custom standard.

So as @jrfnl has said, we'll need to know what that standard is and how you are running PHPCS. Then we can debug the problem and figure out if two sniffs are conflicting during auto-fixing.

**Comment by justinblayney** [comment] 2019-08-13 13:54
I didn't set a standard, I just ran it with the default installation.

**Comment by justinblayney** [comment] 2019-08-13 13:57
If i need to set a standard, please point in in the right direction. I am upgrading the site to php 7.3, so i would like it to follow that standard

**Comment by gsherwood** [comment] 2019-08-13 22:17
> I didn't set a standard, I just ran it with the default installation.

That would be the PEAR standard then.

I ran the PEAR standard over the sample code you provided and it `FOUND 34 ERRORS AND 5 WARNINGS AFFECTING 23 LINES`. I ran PHPCBF over the file using the PEAR standard and it fixed 33 errors and left 5 unfixed. No errors were reported.

To replicate this issue, I really need a code sample that shows the error occurring. Can you please provide one?

**Comment by justinblayney** [comment] 2019-08-16 18:43
ok so i an this today and got this error

$ phpcbf -w --standard=PSR2 --encoding=utf-8 --extensions=php,inc,lib,js,css,html --runtime-set testVersion 7.3 ./artist.php

Changing into directory /administration
Processing artist.php [PHP => 1184 tokens in 240 lines]... DONE in 98ms (77 fixable violations)
        => Fixing file: 1/77 violations remaining [made 50 passes]... ERROR in 3.6 secs
No fixable errors were found
Time: 3.76 secs; Memory: 14Mb

**Comment by gsherwood** [comment] 2019-08-18 23:39
Any chance you could paste the entire content of the artist.php file, or a smaller file that shows the same result?

**Comment by gsherwood** [comment] 2019-09-23 22:19
Closing due to inability to replicate the issue. If you can find a smaller code snippet that replicates the problem, please post it and I'll take another look.

**Closed by gsherwood** 2019-09-23 22:19 UTC
Labels: Awaiting Feedback
