### ISSUE TITLE
Always try to load phpcs.xml from current folder

### ISSUE THREAD

**Issue by cweiske** [squizlabs/PHP_CodeSniffer#789] opened 2015-11-26 08:03 UTC
I've got a project with a `phpcs.xml` file in its root folder. It gets used when I run `phpcs` without parameters.

Now I wanted to check a certain folder only, but when doing so `phpcs.xml` does not get loaded:

```
$ strace -estat phpcs  2>&1|grep phpcs.xml
stat("/home/cweiske/php/phpcstest/phpcs.xml", {st_mode=S_IFREG|0664, st_size=606, ...}) = 0
$ strace -estat phpcs Classes  2>&1|grep phpcs.xml
$
```

This gives totally different results for both runs, and makes it impossible to check single folders while using `phpcs.xml`.

**Comment by gsherwood** [comment] 2015-11-26 08:14
This is a duplicate of issue #626 , which I actually added to master yesterday. So this will be released in the next version, or grab it fro master now.

**Closed by gsherwood** 2015-11-26 08:14 UTC
