### ISSUE TITLE
PHPCBF can make invalid fixes to inline JS control structures that make use of JS objects

### ISSUE THREAD

**Issue by conantran** [squizlabs/PHP_CodeSniffer#1432] opened 2017-04-26 08:22 UTC
Hello,

I ran phpcbf on the following javascript code: (notice the use of short hand, no open and close brackets which is violating psr2

```javascript
if ($("#myid").rotationDegrees()=='90')
    $('.modal').css({'transform': 'rotate(90deg)'});
```
and it modify the above as: (notice how phpcbf add open bracket in the if control statement but failed to add the closing bracket, also it removed bracket in the `.css`line
```javascript
if ($("#myid").rotationDegrees()=='90') {
    $('.modal').css('transform': 'rotate(90deg)'});
```
which produced an javascript error exception in browser. However, if I ran phpcbf on the following (added open and close brackets and spaces)

```javascript
if ($("#myid").rotationDegrees()=='90') {
    $('.modal').css(   {'transform': 'rotate(90deg)'});
}
```
the tools run ok.

I think this is not expected, I would expect the phpcbf to fix the above by adding opening and closing bracket in the control structure but not modifying what within it.

**Comment by gsherwood** [comment] 2017-04-26 23:58
The problem is that the tokenizer thinks the first `{` is the opening curly brace for the `if`. If it didn't, it would correctly report this as an inline control structure and a different sniff would find and fix that.

**Comment by conantran** [comment] 2017-04-27 00:04
thanks @gsherwood, by saying a different sniff would find and fix that, what do you mean by that?

this broke my javascript and after the sniff try to fix the code style though so i'm not at all 100% confident to run the auto code fix now.

**Comment by gsherwood** [comment] 2017-04-27 00:28
> by saying a different sniff would find and fix that, what do you mean by that?

The sniff that detects and fixes inline control structures would find and fix this. The sniff that is causing it to break would ignore this code because the control structure doesn't have any braces.

This is the code I have been testing:
```js
if ($("#myid").rotationDegrees()=='90')
    $('.modal').css({'transform': 'rotate(90deg)'});

if ($("#myid").rotationDegrees()=='90')
    $foo = {'transform': 'rotate(90deg)'};
```
And PHPCS will report these errors (note the sniff codes):
```
FILE: temp.js
----------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
----------------------------------------------------------------------
 1 | ERROR | [x] Expected 1 space after closing parenthesis; found "\n
   |       |     $('.modal').css("
   |       |     (Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis)
 2 | ERROR | [x] Newline required after opening brace
   |       |     (Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace)
 4 | ERROR | [x] Expected 1 space after closing parenthesis; found "\n
   |       |     $foo = "
   |       |     (Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis)
 5 | ERROR | [x] Newline required after opening brace
   |       |     (Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 4 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```
After fixing the tokenizer, you get these errors instead:
```
FILE: temp.js
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 1 | ERROR | [x] Inline control structures are not allowed
   |       |     (Generic.ControlStructures.InlineControlStructure.NotAllowed)
 4 | ERROR | [x] Inline control structures are not allowed
   |       |     (Generic.ControlStructures.InlineControlStructure.NotAllowed)
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
```
And now PHPCBF fixes the file correctly by adding braces:
```diff
--- temp.js
+++ PHP_CodeSniffer
@@ -1,5 +1,7 @@
-if ($("#myid").rotationDegrees()=='90')
+if ($("#myid").rotationDegrees()=='90') {
     $('.modal').css({'transform': 'rotate(90deg)'});
+}

-if ($("#myid").rotationDegrees()=='90')
+if ($("#myid").rotationDegrees()=='90') {
     $foo = {'transform': 'rotate(90deg)'};
+}
```
NOTE that this assumes your standard has included the `Generic.ControlStructures.InlineControlStructure` sniff. If it doesn't include this sniff, PHPCBF will not make any changes to your code.

**Comment by gsherwood** [comment] 2017-04-27 00:34
I've pushed up a fix for this issue, to be included in the next 2.x and 3.x releases. Thanks for the report.

**Closed by gsherwood** 2017-04-27 00:34 UTC
Labels: Bug
