### ISSUE TITLE
Double arrow tokenized as T_STRING when placed after function named "fn"

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2865] opened 2020-02-11 05:18 UTC
Given the below code sample, PHP itself tokenizes the `=>` as `T_DOUBLE_ARROW`, however, since PHPCS 3.5.4, PHPCS tokenizes it as `T_STRING`.

I haven't traced back yet which commit introduced this, nor figured out yet where to apply the fix.

```php
class Foo {
    public $fn = 'key';

    public function bar() {
        return [
            $this->fn => 'value',
        ];
    }
}
```

https://3v4l.org/OXelC

Related to #2523

**Comment by gsherwood** [comment] 2020-03-09 21:19
This issue is caused by this change: https://github.com/squizlabs/PHP_CodeSniffer/commit/0e4fe7404d19701687c27a2991feae9641fa7359

**Comment by gsherwood** [comment] 2020-03-09 21:36
The previous change also included the changing of the function name token into a string, which wasn't required for arrow functions, and actually caused a problem given it assumed the next token as a name. Even though the function being called is not actually an arrow function, that decision doesn't happen until `processAdditional()`, so it looks like one on the first pass.

This is fixed now. Thanks for reporting it.

**Closed by gsherwood** 2020-03-09 21:36 UTC
Labels: Bug

**Comment by jrfnl** [comment] 2020-03-09 21:44
@gsherwood Thanks for fixing this!
