### ISSUE TITLE
Forcing opposite behavior of rule

### ISSUE THREAD

**Issue by PatricNox** [squizlabs/PHP_CodeSniffer#3005] opened 2020-07-05 14:33 UTC
Hey, 

incredibly dumb question though something that would ease and simplify stuff instead of being forced to install custom rules:

Is it possible to force the **opposite** behavior of a rule? 

```
 13 | ERROR | Tag @return cannot be grouped with parameter tags in a doc comment
    |       | (Generic.Commenting.DocComment.NonParamGroup)
```

In Laravel, the very opposite is the _correct_ standard, so would it be possibly to force it **to be** grouped with parameter tags? 

```
    <rule ref="Generic.Commenting.DocComment">
        <exclude name="Generic.Commenting.DocComment.TagValueIndent"/>
        <opposite name="Generic.Commenting.DocComment.NonParamGroup"/>
    </rule>
```

**Comment by jrfnl** [comment] 2020-07-05 17:29
@PatricNox There are no dumb questions.

Having said that, this would not be an easy feature to implement, as all sniffs - especially those with fixers - would need to implement both the code to allow for the originally intended behaviour as well as for the opposite.

There are a number of sniffs which do allow some form of this through properties, most notably whitespace related sniffs, where you can set a `spacing` property. This will allow you to, for instance, enforce a single space instead of no whitespace in certain places.

For a [full list of customizable properties](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties) for the PHPCS native sniffs and what they do, have a look in the wiki.

Not the answer you are looking for, but hopefully it will help a bit anyhow.

**Comment by gsherwood** [comment] 2020-07-05 22:26
Thanks @jrfnl for the answer. I'm going to close this as it is a good generic question and answer.

If you want to open a feature request for a sniff property to group the @return tag with others in a doc comment (or any other settings) please do, although it's not something I have time to work on so it would need help from the wider developer community.

**Closed by gsherwood** 2020-07-05 22:26 UTC

**Comment by PatricNox** [comment] 2020-07-12 13:23
@jrfnl  @gsherwood  thank you both for your answers, I'm satisfied to hear such support and respectful replies. 

Unfortunately, hacking around with whitespaces, would make problems elsewhere so I decided to have this part covered in the PR stage until myself or someone else got the time to add this functionality. 

Thanks.
