### ISSUE TITLE
Allow Generic.CodeAnalysis.UnusedFunctionParameter to ignore parameters whose name starts with an underscore

### ISSUE THREAD

**Issue by mwgamble** [squizlabs/PHP_CodeSniffer#2398] opened 2019-02-05 03:22 UTC
It's a common convention to be able to mark a parameter as explicitly unused by prefixing its name with an underscore. This is sometimes necessary when you need to fulfil a contract, such as implementing an interface, overriding a method, or providing a method that is designed to be overridden but otherwise requires no default behaviour.

**Comment by jrfnl** [comment] 2019-02-05 18:59
Duplicate of #1962

**Comment by gsherwood** [comment] 2019-02-05 21:21
Closing as duplicate

**Closed by gsherwood** 2019-02-05 21:21 UTC
Labels: Enhancement
