### ISSUE TITLE
3.0.0RC1 PHAR does not work with PEAR standard

### ISSUE THREAD

**Issue by sebastianbergmann** [squizlabs/PHP_CodeSniffer#1167] opened 2016-09-21 13:13 UTC
```
$ php-56 --version
PHP 5.6.26-dev (cli) (built: Aug 22 2016 18:36:51) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0-dev, Copyright (c) 2002-2016, by Derick Rethans
```

```
$ php-70 --version
PHP 7.0.11-dev (cli) (built: Aug 20 2016 08:33:54) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0-dev, Copyright (c) 2002-2016, by Derick Rethans
```

```
$ wget https://github.com/squizlabs/PHP_CodeSniffer/releases/download/3.0.0RC1/phpcs.phar
```

```
$ php-56 phpcs.phar

Fatal error: Cannot redeclare class PHP_CodeSniffer\Standards\PEAR\Sniffs\Commenting\FileCommentSniff in phar:///home/sb/phpcs.phar/src/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php on line 2

Call Stack:
    0.0031     439840   1. {main}() /home/sb/phpcs.phar:0
    0.0044     605176   2. PHP_CodeSniffer\Runner->runPHPCS() /home/sb/phpcs.phar:6
    0.0097    1074472   3. PHP_CodeSniffer\Runner->init() phar:///home/sb/phpcs.phar/src/Runner.php:2
    0.0121    1376416   4. PHP_CodeSniffer\Ruleset->__construct() phar:///home/sb/phpcs.phar/src/Runner.php:2
    0.0138    1392984   5. PHP_CodeSniffer\Ruleset->registerSniffs() phar:///home/sb/phpcs.phar/src/Ruleset.php:2
    0.0155    1565152   6. PHP_CodeSniffer\Autoload::loadFile() phar:///home/sb/phpcs.phar/src/Ruleset.php:2
    0.0160    1716192   7. include('phar:///home/sb/phpcs.phar/src/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php') phar:///home/sb/phpcs.phar/autoload.php:2
```

```
$ php-70 phpcs.phar 

Fatal error: Cannot declare class PHP_CodeSniffer\Standards\PEAR\Sniffs\Commenting\FileCommentSniff, because the name is already in use in phar:///home/sb/phpcs.phar/src/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php on line 2

Call Stack:
    0.0034     576328   1. {main}() /home/sb/phpcs.phar:0
    0.0045     684240   2. PHP_CodeSniffer\Runner->runPHPCS() /home/sb/phpcs.phar:6
    0.0103     966632   3. PHP_CodeSniffer\Runner->init() phar:///home/sb/phpcs.phar/src/Runner.php:2
    0.0126    1156344   4. PHP_CodeSniffer\Ruleset->__construct() phar:///home/sb/phpcs.phar/src/Runner.php:2
    0.0146    1166344   5. PHP_CodeSniffer\Ruleset->registerSniffs() phar:///home/sb/phpcs.phar/src/Ruleset.php:2
    0.0160    1290656   6. PHP_CodeSniffer\Autoload::loadFile() phar:///home/sb/phpcs.phar/src/Ruleset.php:2
    0.0166    1378240   7. include('phar:///home/sb/phpcs.phar/src/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php') phar:///home/sb/phpcs.phar/autoload.php:2
```

**Comment by gsherwood** [comment] 2016-09-21 23:02
Problem was caused by code relying on `realpath()` to remove relative references, which it wont do in a phar. Changed code to not use relative paths in this case.

Only happened in the PEAR standard as ClassCommentSniff autoloads FileCommentSniff before the ruleset has a chance to include it manually. It seems the order of all other sniffs works out to have the ruleset load the file directly before any autoloading takes place.

Thanks for the bug report.

**Comment by birkett** [comment] 2017-01-28 15:11
Still seeing this with RC2 - exactly the same.

**Comment by gsherwood** [comment] 2017-01-29 23:27
@birkett Are you sure you have RC2? I've downloaded a fresh copy and tested it. It's still working fine.

**Comment by birkett** [comment] 2017-01-30 09:13
Yes - 3.0.0RC2.
Using the PHAR, on Windows, with PHP 7.1.1. All PHP related commands and tools are being run under MSYS (Git Bash).

**Comment by gsherwood** [comment] 2017-01-30 23:43
I've managed to replicate the issue now. I get:
```
Fatal error: Cannot declare class 
PHP_CodeSniffer\Standards\PEAR\Sniffs\Commenting\FileCommentSniff,
because the name is already in use in 
phar://D:/PHP_CodeSniffer/phpcs.phar/src/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php
on line 2
```

**Comment by gsherwood** [comment] 2017-01-31 00:20
I've found the new problem - inconsistent directory separators were causing the file to be included twice by the autoloader. This will be released in RC3.

**Closed by gsherwood** 2017-01-31 00:20 UTC
Labels: Bug
