### ISSUE TITLE
Feature - Only format modified text

### ISSUE THREAD

**Issue by shivapoudel** [squizlabs/PHP_CodeSniffer#3111] opened 2020-09-10 19:41 UTC
VSCode 1.49.0 comes with setting the only format modified text using the setting `"editor.formatOnSaveMode": "modifications",`. Do PHPCBF come with a setting to format only the modified area of the file?

**Comment by gsherwood** [comment] 2020-09-10 23:35
Use can use the `--filter=gitmodified` CLI arg to only format files that have modifications, but there is no feature to format just the lines that have been modified. This often doesn't make sense for the sniffs as they may generate errors on lines that have not changed, but the errors are caused by changes that were made elsewhere in the file.

**Comment by shivapoudel** [comment] 2020-09-16 19:10
I was talking about to adapt this VSCode feature https://code.visualstudio.com/updates/v1_49#_only-format-modified-text in its extension https://github.com/valeryan/vscode-phpsab/issues/31

**Comment by valeryan** [comment] 2020-09-16 19:44
My vscode extension does not have any association with phpcs beyond utilizing it. I assume this issue would be better handled on my extension. @gsherwood I would close this...

**Comment by gsherwood** [comment] 2020-09-20 23:09
Good discussion, but closing as this is not something that is going to be handled at the PHPCS level.

**Closed by gsherwood** 2020-09-20 23:09 UTC
