### ISSUE TITLE
Setting Sniff Properties per-file

### ISSUE THREAD

**Issue by sirbrillig** [squizlabs/PHP_CodeSniffer#2424] opened 2019-02-15 01:54 UTC
Originally suggested for my standard in https://github.com/sirbrillig/phpcs-variable-analysis/issues/45 I wonder if it might be useful to allow setting sniff properties (options for a specific sniff) within a file to apply only to that file.

Maybe something like [Configuration Comments in eslint](https://eslint.org/docs/user-guide/configuring#using-configuration-comments)

**Comment by jrfnl** [comment] 2019-02-15 02:20
Duplicate of #2126 ?

**Comment by gsherwood** [comment] 2019-02-15 09:07
> Duplicate of #2126 ?

I think so. You're probably looking for the phpcs:set annotation, but it's not localised to a single file at this time. Please comment over there if you have additional requirements.

**Closed by gsherwood** 2019-02-15 09:07 UTC

**Comment by sirbrillig** [comment] 2019-02-15 15:49
Thanks! Much appreciated. I could have sworn I saw that something like `//phpcs:set` but I couldn't locate it in the docs.
