### ISSUE TITLE
How to debug "unterminated comment" files

### ISSUE THREAD

**Issue by davidfavor** [squizlabs/PHP_CodeSniffer#1613] opened 2017-08-15 17:12 UTC
Currently no filename emits from Tokenizer problems.

Someone let me know how to determine the related file.

https://github.com/squizlabs/PHP_CodeSniffer/issues/1612 might solve this.
```
net8-rmt-lowres # time nice -19 phpcs -v --parallel=32 --ignore="*modernizr*,*/backup*,*.min.*" -d xdebug.show_exception_trace=0 -p --standard=PHPCompatibility --runtime-set testVersion 7.1 htdocs

Registering sniffs in the PHPCompatibility standard... DONE (62 sniffs registered)
Creating file list... DONE (1527 files in queue)
PHP Warning:  Unterminated comment starting line 1 in /usr/share/php/PHP/CodeSniffer/src/Tokenizers/PHP.php on line 467
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpcs:0
PHP   2. PHP_CodeSniffer\Runner->runPHPCS() /usr/bin/phpcs:18
PHP   3. PHP_CodeSniffer\Runner->run() /usr/share/php/PHP/CodeSniffer/src/Runner.php:114
PHP   4. PHP_CodeSniffer\Runner->processFile() /usr/share/php/PHP/CodeSniffer/src/Runner.php:462
PHP   5. PHP_CodeSniffer\Files\LocalFile->process() /usr/share/php/PHP/CodeSniffer/src/Runner.php:580
PHP   6. PHP_CodeSniffer\Files\LocalFile->process() /usr/share/php/PHP/CodeSniffer/src/Files/LocalFile.php:94
PHP   7. PHP_CodeSniffer\Files\LocalFile->parse() /usr/share/php/PHP/CodeSniffer/src/Files/File.php:304
PHP   8. PHP_CodeSniffer\Tokenizers\CSS->__construct() /usr/share/php/PHP/CodeSniffer/src/Files/File.php:498
PHP   9. PHP_CodeSniffer\Tokenizers\CSS->__construct() /usr/share/php/PHP/CodeSniffer/src/Tokenizers/CSS.php:38
PHP  10. PHP_CodeSniffer\Tokenizers\CSS->tokenize() /usr/share/php/PHP/CodeSniffer/src/Tokenizers/Tokenizer.php:69
PHP  11. PHP_CodeSniffer\Tokenizers\CSS->tokenize() /usr/share/php/PHP/CodeSniffer/src/Tokenizers/CSS.php:191
PHP  12. token_get_all() /usr/share/php/PHP/CodeSniffer/src/Tokenizers/PHP.php:467
```

**Comment by gsherwood** [comment] 2017-08-15 23:28
You've got verbose output on, and it shows that no files have started processing yet. It hasn't even changed into the first directory to begin processing, so it might be a problem with a custom sniff or ruleset.

The best thing to do is to use `-vv` instead of `-v`, drop the `---parallel`, and see what output you get. You should get a lot of ruleset parsing output at the top, possibly followed by a bunch of tokenizer output if any sniffs are using generic pattern matching. Maybe something in there will help.

Failing that, I'd try just running the standard on a single file and see if you can replicate it. Or try using one of the built-in standards, like PSR2, and see if you get the same error.

**Comment by davidfavor** [comment] 2017-08-17 01:24
Running...
```
phpcs -vvv --standard=PSR2 --runtime-set testVersion 7.1 media-query.css > phpcs.crash.txt 2>&1
```
Attached are the log file + the .css file causing the crash.

Fix for now is to just skip this file or use --extension="php,inc,lib"

[phpcs.crash.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/1229890/phpcs.crash.txt)

[media-query.css.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/1229891/media-query.css.txt)

**Comment by gsherwood** [comment] 2017-08-17 03:25
That error in your crash file is actually caused by the `-vv` exposing a bug in the CSS tokenizer. That file actually processes correctly. I've committed a fix for that verbose output error, but you'll need to grab the latest master code to get that fix, or patch the tokenizer manually.

Note that this error would occur when processing any CSS file using `-vv` and it wouldn't be related to your original error. So you'll need to run the command again to see if you can replicate the original issue.

**Comment by davidfavor** [comment] 2017-08-17 15:06
Works like a charm now.

Thanks!

**Comment by davidfavor** [comment] 2017-08-17 16:11
Original error is resolved now too.

**Closed** 2017-08-22 22:35 UTC
Labels: Question
