### ISSUE TITLE
Unused parameter false positive when using array index in arrow function

### ISSUE THREAD

**Issue by ghnp5** [squizlabs/PHP_CodeSniffer#3284] opened 2021-03-29 23:12 UTC
Hello,

This works fine:

	$found = in_array_cb($needle, $haystack, function($array, $needle) {
		return $array[2] === $needle;
	});

But in the bellow, PHPCS complains with "The method parameter $needle is never used" (`Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed`):

	$found = in_array_cb($needle, $haystack, fn($array, $needle) => $array[2] === $needle);

If I remove "[2]", PHPCS does not complain:

	$found = in_array_cb($needle, $haystack, fn($array, $needle) => $array === $needle);

**Comment by gsherwood** [comment] 2021-03-29 23:50
Looks like this is caused by the T_FN end token matching, and something in the sniff itself. I've fixed the T_FN end token but still confirming that, and looking into the sniff.

**Comment by gsherwood** [comment] 2021-03-30 00:05
I've pushed a fix for this now. Thanks for reporting it.

**Closed by gsherwood** 2021-03-30 00:05 UTC
Labels: Bug
