### ISSUE TITLE
Provide and option to sniff and fix only the git diff. Donot sniff and fix the entire file

### ISSUE THREAD

**Issue by sridhav** [squizlabs/PHP_CodeSniffer#758] opened 2015-10-31 02:25 UTC
Some devs like to update only their git diff file but not the entire file so that they can have a pretty commit history. An option is required to sniff and fix only the git diff part rather than entire file.

**Comment by aik099** [comment] 2015-10-31 08:16
This is duplicate of #678.

**Comment by gsherwood** [comment] 2015-10-31 09:32
Yes, this is a duplicate, and PHPCS still wont be able to do this. It's best done outside PHPCS.

**Closed by gsherwood** 2015-10-31 09:32 UTC
