### ISSUE TITLE
Bad indentation detection in Generic.WhiteSpace.ScopeIndent

### ISSUE THREAD

**Issue by ondrejmirtes** [squizlabs/PHP_CodeSniffer#792] opened 2015-11-26 19:30 UTC
Immediate `return`s in switch case statements expect one more tab than expected after upgrading PHPCS to 2.4.0:

```php
	/**
	 * @param \Slevomat\User\UserGender $gender
	 * @return integer[]
	 */
	protected function getCategoriesRelevantForGender(UserGender $gender)
	{
		switch (true) {
			case $gender->equalsValue(UserGender::FEMALE):
				return [ProductCategory::FASHION_FOR_FEMALE, ProductCategory::FASHION_FOR_CHILDREN]; // Line indented incorrectly; expected 4 tabs, found 3 (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
			case $gender->equalsValue(UserGender::MALE):
				return [ProductCategory::FASHION_FOR_MALE]; // Line indented incorrectly; expected 4 tabs, found 3 (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
			default:
				return [ProductCategory::FASHION];
		}
	}
```

**Comment by gsherwood** [comment] 2015-11-26 21:06
This is a duplicate of #786 , which has been fixed in master. The issue is actually the short array syntax in the return and not the return statement itself.

**Closed by gsherwood** 2015-11-26 21:06 UTC
