### ISSUE TITLE
PHP 8 | Constructor Promotion indentation

### ISSUE THREAD

**Issue by vstyler96** [squizlabs/PHP_CodeSniffer#3190] opened 2020-12-30 17:41 UTC
**Describe the bug**
When using PSR12 standard with Constructor Promotion is not supported, request 4 spaces instead 0f 8.
**Code sample**
```php
<?php

namespace Examples\ConstructorPromotion;

class ConstructorExample
{
    public function __construct(
        protected bool $exampleBool = false,
        protected array $exampleArray = [],
        protected string $exampleString = ''
    ) {}
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php ...`
3. See error message displayed
```
FILE: /srv/test/test.php
------------------------------------------------------------------------
FOUND 11 ERRORS AFFECTING 11 LINES
------------------------------------------------------------------------
 13 | ERROR | [x] Line indented incorrectly; expected 4 spaces, found 8
 14 | ERROR | [x] Line indented incorrectly; expected 4 spaces, found 8
 15 | ERROR | [x] Line indented incorrectly; expected 4 spaces, found 8
```

**Expected behavior**
Not show the error messages.

**Versions:**
 - OS: Arch Linux
 - PHP: PHP 8
 - PHPCS: ^3.5
 - Standard: PSR12

**Additional context**
I am updating my project to PHP 8 but some of the new features are not supported.

**Comment by jrfnl** [comment] 2020-12-30 18:13
Duplicate of #3167 which has already been fixed. The fix will be included in the 3.6.0 release.

**Closed** 2020-12-30 20:26 UTC

**Comment by someniatko** [comment] 2021-04-21 09:43
@jrfnl Hi, this concrete example still doesn't work on 3.6.0 with `PSR12` ruleset:

```php
final class Credentials
{
    public function __construct(
        public string $login,
        public string $password,
    ) {}
}
```

```
 13 | ERROR | [x] Closing brace must be on a line by itself
    |       |     (Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore)
```

This works but looks ugly:

```php
    public function __construct(
        public string $login,
        public string $password,
    ) {
    }
```

**Comment by jrfnl** [comment] 2021-04-21 14:02
@someniatko That's a completely different error than discussed in this issue. Please see #3278 and #3291 for discussion about it.
