### ISSUE TITLE
Properties of custom sniffs cannot be configured

### ISSUE THREAD

**Issue by Pittiplatsch** [squizlabs/PHP_CodeSniffer#432] opened 2015-01-14 17:09 UTC
The following does not work:
```
    <rule ref="path/to/my/Custom/Sniff.php">
        <properties>
            <property name="foo" value="bar" />
        </properties>
    </rule> 
```
https://github.com/squizlabs/PHP_CodeSniffer/blob/738a2775866c94ee614b54c2058af5e2ce27362c/CodeSniffer.php#L1182 sets the properties to `$this->ruleset[$code]['properties']` with `$code` being `path/to/my/Custom/Sniff.php`, while on actually pushing the properties into the sniffer instance in https://github.com/squizlabs/PHP_CodeSniffer/blob/738a2775866c94ee614b54c2058af5e2ce27362c/CodeSniffer.php#L1344 `$code` contains the "short" name `Custom.Sniff`, which obviously doesn't match the array structure `$this->ruleset`.

**Comment by aik099** [comment] 2015-01-14 18:28
Of course. This is because you need to specify sniff code, not PHP file path, which contains the sniff.

Also using relative/absolute paths to sniffs might not work.

**Comment by aik099** [comment] 2015-01-14 18:29
Example of all possible directives in `ruleset.xml`: http://pear.php.net/manual/en/package.php.php-codesniffer.annotated-ruleset.php

**Comment by Konafets** [comment] 2015-01-14 18:31
If you use a custom sniff you can use relative paths and you need to use the path to the file
Here is an example:
https://github.com/typo3-ci/TYPO3CMS/blob/develop/ruleset.xml#L36

**Comment by gsherwood** [comment] 2015-01-14 22:31
As already mentioned, you need to use the sniff code to set sniff properties, in the same way you need the message code to set message properties.

So in your case, you'll need to include the sniff and using the path and then you can set the properties of that sniff:
```xml
<rule ref="path/to/my/Custom/Sniff.php" />
<rule ref="Standard.Category.CustomSniff">
    <properties>
        <property name="foo" value="bar" />
    </properties>
</rule>
```

Does that work ok for you?

**Comment by Pittiplatsch** [comment] 2015-01-15 00:00
Sorry, obviously I didn't describe the problem clear enough.
It *is* possible to include sniffs by specifying the absolute path - that's what I did first. Don't know if this is "undocumented behaviour", but it works.
The actual problem is that properties aren't passed to the sniff.

@gsherwood Wow, didn't ever think of this (kinda dirty) possibilty. Will try this one out tomorrow, but I think it should work, if the double definition doesn't have any side effects.

**Comment by gsherwood** [comment] 2015-01-15 00:35
> Wow, didn't ever think of this (kinda dirty) possibilty

It's not dirty. It's the support and documented method of doing this. If it doesn't work, then I need to fix that.

**Comment by aik099** [comment] 2015-01-15 07:57
@gsherwood , what I think @Pittiplatsch means by dirty is that you need to specify `rule` node twice for same sniff. Isn't it possible to allow specifying properties and other stuff right within 1st rule node (with `.php` in it)?

**Comment by Pittiplatsch** [comment] 2015-01-15 09:18
Ok. So please help me out - am I missing any doc resource, where I can find more tricks like this?

**Comment by Pittiplatsch** [comment] 2015-01-15 11:31
@gsherwood Your approach doesn't work out of the box.
```
<ruleset>
    <rule ref="path/to/MyStandard/Foo/BarSniff.php" />
    <rule ref="MyStandard.Foo.Bar">
        <properties>
            <property name="propName" value="propValue" />
        </properties>
    </rule>
</ruleset>
```
(Hope I didn't introduce slips on transcription of production code)
The reason I specify the sniff's absolute path is to avoid specifying and pumping `install_path` - anyway I couldn't think of any other reason.

The sniff specified via absolute path is found and triggered, however the notation via short name results in `PHP_CodeSniffer_Exception: Referenced sniff "MyStandard.Foo.Bar" does not exist`.

**Comment by gsherwood** [comment] 2015-01-15 22:44
Thanks a lot for testing this. I'll look into why it isn't working. I'll also see if I can get it working when you use the path instead of the sniff code, but I'm not sure what that will involve yet.

**Comment by derhasi** [comment] 2015-01-26 08:29
I stumbled upon the same problem. The problem is locatedn in [populateTokenListeners](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer.php#L1360), as there is no reference stored between the file (relative path used in ruleset) and the short reference name of the rule/sniff. Maybe it would improve overall quality, if there was a ConverterObject that will register and convert paths (absolute, relative), short references and class names from one type to the other.

**Comment by gsherwood** [comment] 2015-03-02 22:27
I've committed a fix to get the properties (and other settings) working correctly for custom sniffs, but you will need to use the sniff code and not the full file path to make it work. So that means using this code:
```xml
<rule ref="path/to/my/Custom/Sniff.php" />
<rule ref="Standard.Category.CustomSniff">
    <properties>
        <property name="foo" value="bar" />
    </properties>
</rule>
```

**Closed by gsherwood** 2015-03-02 22:27 UTC
Labels: Bug

**Comment by 1099511627776** [comment] 2016-06-04 17:38
Sorry for "UP-ing" this issue but I have a problem assigning properties to my custom sniff from ruleset and i HOPE that some one here can help me.
I'm using the latest PHAR archive "(PHP_CodeSniffer version 2.6.0 (stable) by Squiz (http://www.squiz.net)"
My ruleset.xml file looks like this:
```
<ruleset name="GMEStandard">
 <description>GME Standard</description>
 <rule ref="./GMEStandard/Sniffs/ValidVariableName/HungarianNotationSniff.php">
 </rule>
 <rule ref="GMEStandard.Sniffs.ValidVariableName.HungarianNotationSniff">
    <properties>
        <property name="reservedWords" value="$start,$end" />
        <property name="allowedPrefixess" value="123123" />
    </properties>
 </rule>
</ruleset>
```
and when i try to run phpcs (php ./phpcs.phar --standard=GMEStandard), I get an exception:

```
PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "GMEStandard.Sniffs.ValidVariableName.HungarianNotationSniff" does not exist' in phar:///home/hackers/Devel/gmeads/vendor/phpcs.phar/CodeSniffer.php:1137
Stack trace:
#0 phar:///home/hackers/Devel/gmeads/vendor/phpcs.phar/CodeSniffer.php(757): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/home/hackers/D...', 0)
#1 phar:///home/hackers/Devel/gmeads/vendor/phpcs.phar/CodeSniffer.php(561): PHP_CodeSniffer->processRuleset('/home/hackers/D...')
#2 phar:///home/hackers/Devel/gmeads/vendor/phpcs.phar/CodeSniffer.php(505): PHP_CodeSniffer->initStandard('GMEStandard', Array)
#3 phar:///home/hackers/Devel/gmeads/vendor/phpcs.phar/CodeSniffer/CLI.php(1116): PHP_CodeSniffer->process(Array, 'GMEStandard')
#4 phar:///home/hackers/Devel/gmeads/vendor/phpcs.phar/CodeSniffer/CLI.php(862): PHP_CodeSniffer_CLI->explainStandard('GMEStandard')
#5 phar:///home/hackers/Devel/gmeads/vendor/phpcs.phar/CodeSniffer/CLI.php(104): PHP_Cod in phar:///home/hackers/Devel/gmeads/vendor/phpcs.phar/CodeSniffer.php on line 1137
```
P.S. If I dont reference a sniff in ruleset.xml it's working fine with default parameters defined in class.

**Comment by aik099** [comment] 2016-06-04 19:14
This is because you need to change

```
<rule ref="GMEStandard.Sniffs.ValidVariableName.HungarianNotationSniff">
```

into

```
<rule ref="GMEStandard.ValidVariableName.HungarianNotation">
```

in your ruleset.

**Comment by 1099511627776** [comment] 2016-06-06 06:47
Thanks, it worked.
