### ISSUE TITLE
False positives on multi-line functions indentation starting with v3.2

### ISSUE THREAD

**Issue by acelaya** [squizlabs/PHP_CodeSniffer#1824] opened 2018-01-02 19:08 UTC
Hi!

I have started to get false positives with the mesage "Multi-line function call not indented correctly; expected 56 spaces but found 58"

The block marking the error is this one

```php
$req = ServerRequestFactory::fromGlobals()->withAttribute('identity', $user)
                                          ->withAttribute(
                                              'transactionId',
                                              (string) $transaction->getPublicId()
                                          );
```

It works if a remove 2 spaces from the second `withAttribute` call, like this

```php
$req = ServerRequestFactory::fromGlobals()->withAttribute('identity', $user)
                                        ->withAttribute(
                                            'transactionId',
                                            (string) $transaction->getPublicId()
                                        );
```

However, this didn't use to mark an error, and now it does. I like to keep methods aligned when using method chaining.

I'm just using the PSR-2 rule.

**Comment by jrfnl** [comment] 2018-01-02 19:33
Duplicate of #1793 ? This has already been fixed in `master`. The fix will be in the 3.2.3 release.

**Comment by acelaya** [comment] 2018-01-02 19:43
Great! I'll try master branch and let you know


--
Alejandro Celaya Alastrué

**Comment by acelaya** [comment] 2018-01-02 23:02
Can confirm that using `dev-master` everything works again as in ^3.1 in my project :-)

**Comment by gsherwood** [comment] 2018-01-02 23:08
Thanks for testing that fix.

**Closed by gsherwood** 2018-01-02 23:08 UTC
Labels: Awaiting Feedback
