### ISSUE TITLE
Bug involving switch and new array syntax (PEAR standards)

### ISSUE THREAD

**Issue by demiankatz** [squizlabs/PHP_CodeSniffer#800] opened 2015-11-30 14:47 UTC
Since Travis updated from 2.2.0 to 2.4.0, my project's build is breaking with false positive errors. It seems to have to do with the way the new array syntax interacts with switch statements.

Simple example:

    <?php

    function foo()
    {
        switch($a) {
        case '1':
            return [1];
        default:
            return;
        }
    }

A call to `phpcs --standard=PEAR test.php` yields:

     8 | ERROR | [x] Line indented incorrectly; expected 8 spaces, found
       |       |     4

However, if I change the code to:

    <?php

    function foo()
    {
        switch($a) {
        case '1':
            return array(1);
        default:
            return;
        }
    }

and run the same phpcs command, everything passes.

A fix to this issue would be greatly appreciated! If I can be of any assistance, please let me know. I am not familiar with this code base, but I'm willing to put some time into a solution if help is needed -- I'd just need some pointers in the right general direction.

**Comment by aik099** [comment] 2015-11-30 15:09
This seems to be a 4th duplicate of original issue reported and fixed in `master`. Have you checked existing recently closed issues before reporting?

Please check if `master` version of PHP_CodeSniffer doesn't produce false positives.

**Comment by demiankatz** [comment] 2015-11-30 15:24
My apologies. I did search for duplicates, but failed to remove the "open" filter.

**Comment by demiankatz** [comment] 2015-11-30 15:26
Also, since the cross-reference was not included earlier, I'll note that the definitive version of the issue appears to be #786.

**Closed** 2015-11-30 21:16 UTC
