### ISSUE TITLE
Return code of phpcbf on all errors fixed

### ISSUE THREAD

**Issue by Tezd** [squizlabs/PHP_CodeSniffer#2954] opened 2020-05-07 23:31 UTC
I have a question regarding this part of the code
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Runner.php#L223
It will return 1 even if all errors are resolved which later will be set as exit code here 
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/bin/phpcbf#L19
Everything which is not 0 considered to be error code.
But in that case it fixed everything should it return 0 instead ?

**Comment by jrfnl** [comment] 2020-05-07 23:54
Duplicate of #1359

Also see: https://github.com/squizlabs/PHP_CodeSniffer/issues/1818#issuecomment-354420927

A revision of the exit codes in on the roadmap for PHPCS 4.x. See #2898

**Comment by Tezd** [comment] 2020-05-08 01:02
Thank you, couldn't find it in issues.

**Closed** 2020-05-08 01:02 UTC
