### ISSUE TITLE
Excluded files still have significant performance impact

### ISSUE THREAD

**Issue by Rarst** [squizlabs/PHP_CodeSniffer#1132] opened 2016-08-26 14:11 UTC
I work on a project with a lot of node dependencies for its JS side. While we exclude `node_modules` from CS scan, its presence seems to significantly bog down performance, even though nothing inside of it is actually scanned.

I get time of 2+ minutes for scan, which goes down to 10 seconds if I delete `node_modules`.

Ruleset & project: https://github.com/Yoast/wordpress-seo/blob/trunk/phpcs.xml (PHPCS and rules in Composer dependencies, run `composer config-yoastcs` for self–contained setup).

**Comment by gsherwood** [comment] 2016-08-28 23:08
Closing this as a duplicate of #933, and #1113.

Summary: this has been resolved in the 3.0 branch (current release there is 3.0.0a1 if you want to test) but is not being brought to the 2.x branch.

**Closed by gsherwood** 2016-08-28 23:08 UTC
