### ISSUE TITLE
Open PHP tag in XML, impacts performance of PHP Tokenizer

### ISSUE THREAD

**Issue by victor-v-rad** [squizlabs/PHP_CodeSniffer#3821] opened 2023-05-10 22:23 UTC
**Describe the bug**
Open PHP tag in XML, impacts performance of PHP Tokenizer

**Custom ruleset**
```xml
<ruleset name="TestXml">
    <arg name="extensions" value="xml"/>
    <rule ref="Generic.Files.InlineHTML">
        <properties>
            <property name="lineLimit" value="420"/>
            <property name="absoluteLineLimit" value="0"/>
        </properties>
    </rule>
</ruleset>
```

**To reproduce**
1. clone https://github.com/venustheme/magento2-image-slider
2. Run `phpcs --standard=path/to/custom_ruleset.xml path/to/magento2-image-slider`

**Actual Results**
phpcs never finishes

**Expected behavior**
phpcs finishes almost instantly

**Versions (please complete the following information):**
 - OS: [MacOS]
 - PHP: [8.2]
 - PHPCS: [master]

**Additional context**
The issue is in this file https://github.com/venustheme/magento2-image-slider/blob/9bba8c275c81997e066cd8e3c87d2498f477692e/etc/widget.xml#L3
<img width="321" alt="image" src="https://github.com/squizlabs/PHP_CodeSniffer/assets/106504/beaa0de5-d36e-4508-9604-86f620ea53ff">
Opened PHP tag in xml file makes PHP Tokenizer parse XML as is it is PHP code

**Comment by jrfnl** [comment] 2023-05-10 22:34
@victor-v-rad The problem is that you are **telling** PHPCS to parse XML files as if they were PHP by having this `<arg name="extensions" value="xml"/>` in your ruleset.

PHPCS is not suitable for analysing XML files and would never attempt to parse them if it wasn't for that `extensions` setting in your ruleset, so the real question is: what are you trying to do with that ? Why is that setting there ?

**Comment by gsherwood** [comment] 2023-05-22 23:05
I'm not sure why there is an open PHP tag in your XML file, but it's causing PHPCS to attempt to parse the XML as PHP.

I'd suggest closing the PHP tag so the file is valid again, or just not telling PHPCS to process XML files as PHP files, as @jrfnl has mentioned already.

**Closed by gsherwood** 2023-05-22 23:05 UTC
Labels: Status: awaiting feedback, Status: close candidate

**Comment by victor-v-rad** [comment] 2023-05-25 04:03
Thank you @gsherwood and @jrfnl for your advises and sorry for the late reply. As a workaround I created dummy tokenizer for xml to be able to sniff and validate xml content.
