### ISSUE TITLE
Switch case indentation error

### ISSUE THREAD

**Issue by milhomem** [squizlabs/PHP_CodeSniffer#802] opened 2015-12-04 16:54 UTC
I'm facing the following error with a switch case in my code.

Line indented incorrectly; expected at least12 spaces, found 8

```php
switch ('b') {
    case 'a':
        return '';
        break;
    case 'b':
        return [];
        break;
    default:
        break;
}
```

**Comment by aik099** [comment] 2015-12-04 17:10
Please try searching for previously reported issues about same topic (including closed ones) before reporting. In this case this is 5th duplicate of issue, that was already fixed in `master`, but might not be released yet.

**Comment by milhomem** [comment] 2015-12-04 17:16
I tried it only in open ones and in change log with no luck. Sorry for that.

**Closed** 2015-12-04 17:16 UTC

**Comment by gsherwood** [comment] 2015-12-04 19:42
> I tried it only in open ones and in change log with no luck. Sorry for that.

Not a problem. Better to report it a second time than not report it at all.
