### ISSUE TITLE
Since `3.7.0` methods named `empty` are failing Squiz.Functions.FunctionDeclaration.Found

### ISSUE THREAD

**Issue by bburnichon** [squizlabs/PHP_CodeSniffer#3613] opened 2022-06-14 08:32 UTC
**Describe the bug**

**Code sample**
```php
<?php

namespace Foo;

class Foo
{
    public function empty(): bool
    {
        return true;
    }
}
```

**Custom ruleset**
Using PSR12 ruleset

**To reproduce**
1. Create a file called `Foo.php` with the code sample above...
2. Run `phpcs --standard=psr12 Foo.php`
3. See error message displayed
```
$ ./vendor/bin/phpcs --standard=psr12 -s Foo.php 

FILE: /projects/PHPCS_Issue/Foo.php
-----------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------
 7 | ERROR | Expected "function abc(...)"; found "function abc(...)"
   |       | (Squiz.Functions.FunctionDeclaration.Found)
-----------------------------------------------------------------------------------------------------------------

Time: 49ms; Memory: 14MB

```

**Expected behavior**
No error should occur. It wasn't with previous version

**Versions (please complete the following information):**
 - OS: Linux
 - PHP: 7.4
 - PHPCS: 3.7.0
 - Standard: PSR12

**Additional context**
Detected by my CI when upgrading PHPCodesniffer to latest release

**Comment by dragosprotung** [comment] 2022-06-14 08:38
Duplicate of #3609. Was fixed in #3610

**Comment by dragosprotung** [comment] 2022-06-14 08:38
@jrfnl any change to get a new version tagged ?

**Comment by jrfnl** [comment] 2022-06-14 08:52
@dragosprotung Not up to me, but I suspect that a new version will be tagged relatively soon. May still be a few days/a week to give people the chance to report any other issues with the 3.7.0 release (and to get those fixed if needed).

**Comment by gsherwood** [comment] 2022-06-14 09:04
What @jrfnl said. Just want to see if anything else comes up over the next day or so.

**Closed by gsherwood** 2022-06-14 09:04 UTC

**Comment by janedbal** [comment] 2022-06-15 10:19
@gsherwood What is wrong tagging it asap? You can tag it again if you find new bugs after the first tag is released, there is nothing wrong with it.

**Comment by gsherwood** [comment] 2022-06-18 07:35
@janedbal @dragosprotung You'll both be happy to know I've tagged a release. 3.7.1 is now available with the fix.
