### ISSUE TITLE
PHP_CodeSniffer detected as backdoor  ?!

### ISSUE THREAD

**Issue by websvcPT** [squizlabs/PHP_CodeSniffer#3044] opened 2020-08-06 15:50 UTC
**Describe the bug**
This has been detected on a college machine 

Windows defender says the file is infected during the installation of CodeSniffer (and other packages)
This seems to be a temporary folder created during installation of packages.

![aba4ce93-6126-4ccb-a583-985ba93c0976](https://user-images.githubusercontent.com/1758961/89551181-8ddfa580-d802-11ea-9a63-bdfe1e90be60.png)

Looking at the file it matches the version on the repo (https://github.com/squizlabs/PHP_CodeSniffer/blob/73e2e7f57d958e7228fce50dc0c61f58f017f9f6/src/Standards/Squiz/Tests/PHP/EvalUnitTest.inc)

**Versions (please complete the following information):**
 - OS: Windows 10
 - PHP: 7.4 (running inside docker)
 - PHPCS: 3.5.5
 - Standard: PSR2

Probably Windows defender is only going mad with those `eval` 
Micro$oft information is not much of a help: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Backdoor:PHP/Dirtelti.MTF&threatId=-2147206067

Any one else had this issue?

**Comment by jrfnl** [comment] 2020-08-06 16:09
Duplicate of #3042

**Closed** 2020-08-07 01:34 UTC
