### ISSUE TITLE
Junit reporter produces invalid XML

### ISSUE THREAD

**Issue by ketumbra** [squizlabs/PHP_CodeSniffer#3383] opened 2021-06-25 17:15 UTC
`phpcs --report-junit=example.test.xml` produces an xml file with multiple `testsuite` elements at the top level. These should be contained in a `testsuites` element.

This prevents ingesting the results into our CI pipeline.

Grateful if this could be fixed. Consider a unit test against the [junit xml schema](https://github.com/junit-team/junit5/blob/43638eb6a870e0d6c49224053dfeb39dcf0ef33f/platform-tests/src/test/resources/jenkins-junit.xsd)

**Comment by jrfnl** [comment] 2021-06-25 17:47
> These should be contained in a `testsuites` element.

They are: https://github.com/nicholascus/PHP_CodeSniffer/blob/16c771d0ac0b4c3e425a4f9c9533d96832e0f08d/src/Reports/Junit.php#L123-L125

Vaguely related: #2964

**Comment by ketumbra** [comment] 2021-06-25 17:48
This is inconsistent. Might be an issue with large projects.

`phpcs --report-junit=example test.xml.` displays the issue where choosing a subfolder does not.
At the same top level `phpcs --report=junit .` does not display any output at all.

**Comment by ketumbra** [comment] 2021-06-25 17:50
Could there be a code path where only `generateFileReport()` is returned but not `generate()`...?

**Comment by jrfnl** [comment] 2021-06-25 18:13
@ketumbra Could you provide _exact_ steps for how to reproduce the issue ?

**Comment by ketumbra** [comment] 2021-06-25 19:45
working on it. I think this is actually a duplicate of #1790. In my project, the subfolders that either:
* contain over 800 php files
* contain minified js
have invalid junit output.  Adding `-d memory_limit 1024M` causes correct output

**Comment by ketumbra** [comment] 2021-06-25 20:00
ah, I see. The file is edited as it goes along so if it crashes, an incomplete file with the correct name is left behind. Can I suggest that the partial results are written to a different file name (e.g. chosename.tmp) and then renamed once complete? Then it will be more obvious that the process has died and not just gone wrong.

Thanks

**Comment by gsherwood** [comment] 2021-07-19 01:31
Closing as duplicate of #1790 as this does appear to be the same issue.

**Closed by gsherwood** 2021-07-19 01:31 UTC
