### ISSUE TITLE
Undefined index: parenthesis_closer in File.php

### ISSUE THREAD

**Issue by paulschreiber** [squizlabs/PHP_CodeSniffer#431] opened 2015-01-14 16:47 UTC
I saw this error:

    PHP Notice:  Undefined index: parenthesis_closer in /usr/local/share/pear/PHP/CodeSniffer/File.php on line 1877

The backtrace was like this, repeated many times:
```
PHP Notice:  Undefined index:  in /usr/local/share/pear/PHP/CodeSniffer/File.php on line 1881
PHP Notice:  Undefined index: parenthesis_closer in /usr/local/share/pear/PHP/CodeSniffer/File.php on line 1877
PHP Notice:  Undefined index:  in /usr/local/share/pear/PHP/CodeSniffer/File.php on line 1881
PHP Notice:  Undefined index: parenthesis_closer in /usr/local/share/pear/PHP/CodeSniffer/File.php on line 1877
```

**Comment by paulschreiber** [comment] 2015-01-14 16:49
The code that caused this problem was:
```php
if ( Foo_Bar::do_thing() {
```

**Comment by aik099** [comment] 2015-01-14 18:29
So this is caused by specific sniff or tokenizer in general?

**Comment by Konafets** [comment] 2015-01-14 18:44
Which version of PHPCS do you are using? Which standard?

**Comment by paulschreiber** [comment] 2015-01-14 18:56
I'm using PHPCS 2.1.0, and WordPress-VIP (with a could of rules disabled).

**Comment by gsherwood** [comment] 2015-01-14 22:18
The notices are caused by the parse error in the code. The piece of code that is causing this notice was actually removed in this commit: https://github.com/squizlabs/PHP_CodeSniffer/commit/07476b9ace133819fd92cc142aa49e507e83a38f

It was causing an unrelated issue with JS files and just didn't need to be there.

Given that the sample code has a parse error in it, any sniffs that are making the (generally fine) assumption that an open parenthesis also has a closing parenthesis might also generate errors. They need to be a bit careful about checking for the closer before assuming it is there. I can't find any included sniffs that have a problem though.

**Closed by gsherwood** 2015-01-14 22:18 UTC
