### ISSUE TITLE
PHP Notice:  in InlineControlStructureSniff.php on line 232

### ISSUE THREAD

**Issue by sirdawidd** [squizlabs/PHP_CodeSniffer#1097] opened 2016-08-02 08:02 UTC
HI,
I'm using codeSniffer 2.6.1 and it produces some errors like
PHP Notice:  Undefined offset: 1951 in Standards\Generic\Sniffs\ControlStructures\InlineControlStructureSniff.php on line 232
InlineControlStructureSniff.php on line 224
InlineControlStructureSniff.php on line 233
Fixer.php on line 350
Fixer.php on line 533
Fixer.php on line 572
DoubleQuoteUsageSniff.php on line 72

This part of code is not even checked if index exists $tokens[$end]['code'].

**Comment by aik099** [comment] 2016-08-02 08:21
Please provide code example and standard used.

**Comment by gsherwood** [comment] 2016-08-02 08:32
I don't need the standard used because the sniff is listed in the error message, but I do need a code sample.

These sort of errors are almost always caused by either the tokenizer not correctly processing a piece of code, or by a syntax error in the code being checked, that is not being handled by the sniff itself.

I've fixed one of these cases recently in the DoubleQuoteUsageSniff. It was caused by a syntax error in the checked file where a double quoted string was being opened by a double quote and closed by a single quote. The code looked like this:
```php
function test() {
    echo "It Worked';
}
```
It produced the same error on line 72 that you are getting. 

Any chance you have a syntax error in your code caused by mismatched quotes?

**Comment by sirdawidd** [comment] 2016-08-03 06:18
Code is valid

```
  public function __construct( $packageId = 0)
    {
        throw new Exception("Package not found with ID($packageId)!");
    }
```

**Comment by gsherwood** [comment] 2016-08-03 06:22
> It's has problems with double quotes, with single it working perfect :)

I can't replicate any problems on that code using any of the included sniffs, for version 2.6.1, 2.6.2 or master.

**Comment by sirdawidd** [comment] 2016-08-03 06:27
My ruleset file has definition  <rule ref="Squiz.Strings.DoubleQuoteUsage" /> of course without it I don't have error

**Comment by aik099** [comment] 2016-08-03 07:09
@sirdawidd , looks like some other sniff in combination with `Squiz.Strings.DoubleQuoteUsage` makes that error. Please provide full standard description or a way to install it locally.

**Comment by gsherwood** [comment] 2016-08-03 08:21
> Than cbf somehow removing first double quote code is invalid, and that's why I have an error

That's interesting given the double quote error is not fixable and so PHPCBF wont be touching that string because of it.

So yes, I'll need to see your ruleset file if possible. That should help track down what is going on.

**Comment by sirdawidd** [comment] 2016-08-04 06:08
The bug was in my sniff.

**Closed** 2016-08-04 06:07 UTC
Labels: Awaiting Feedback

**Comment by gsherwood** [comment] 2016-08-04 06:18
Glad you found it. Thanks for letting me know.
