### ISSUE TITLE
Undefined offset in TodoSniff

### ISSUE THREAD

**Issue by bancer** [squizlabs/PHP_CodeSniffer#693] opened 2015-09-06 09:14 UTC
> Notice: Undefined offset: 1 in /.../app/Vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Generic/Sniffs/Commenting/TodoSniff.php on line 73
Call Stack:
    0.0002     237552   1. {main}() /.../app/Vendor/bin/phpcs:0
    0.1351    1216816   2. PHP_CodeSniffer_CLI->process() /.../app/Vendor/bin/phpcs:39
    0.1704    1272392   3. PHP_CodeSniffer->process() /.../app/Vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php:647
   98.1674    5794792   4. PHP_CodeSniffer->processFile() /.../app/Vendor/squizlabs/php_codesniffer/CodeSniffer.php:488
   98.1676    5795104   5. PHP_CodeSniffer->_processFile() /.../app/Vendor/squizlabs/php_codesniffer/CodeSniffer.php:1351
   98.1677    5795512   6. PHP_CodeSniffer_File->start() /.../app/Vendor/squizlabs/php_codesniffer/CodeSniffer.php:1471
   98.1752    5946488   7. Generic_Sniffs_Commenting_TodoSniff->process() /.../app/Vendor/squizlabs/php_codesniffer/CodeSniffer/File.php:509

phpcs installed by composer: "cakephp/cakephp-codesniffer": "1.*", run with CakePHP standard.
PHP_CodeSniffer version 1.5.6 (stable) by Squiz (http://www.squiz.net)

**Comment by aik099** [comment] 2015-09-06 09:48
Does the same happen on latest released version (2.3.3 if I'm not mistaken)?

**Comment by bancer** [comment] 2015-09-06 21:27
I cannot test it on the latest version because of dependencies.

**Comment by gsherwood** [comment] 2015-09-06 22:35
I think this might be a duplicate of https://github.com/squizlabs/PHP_CodeSniffer/pull/447. The commit is https://github.com/squizlabs/PHP_CodeSniffer/commit/d2cc7e8ae16a47a495f62529e7af20af978c4e20 in case you want to try manually patching seeing as you wont be able to upgrade to 2.3.4 (when released) to get the fix.

**Closed** 2015-12-08 21:52 UTC
Labels: Awaiting Feedback
