### ISSUE TITLE
Bad merge

### ISSUE THREAD

**Issue by andreydiveev** [squizlabs/PHP_CodeSniffer#1584] opened 2017-07-31 16:16 UTC
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Tests/PHP/HeredocUnitTest.inc

**Comment by jrfnl** [comment] 2017-07-31 16:21
Duplicate of #1314. This is a valid test case.

**Closed** 2017-07-31 22:38 UTC
