### ISSUE TITLE
phpcs doesn't see obvious syntax errors

### ISSUE THREAD

**Issue by dvhx** [squizlabs/PHP_CodeSniffer#3740] opened 2023-01-07 23:09 UTC
<?php
    /**
    Phpcs thinks this file is ok
    php version 8.1.2
    
    @category Asdf
    @package  Asdf
    @author   Me <me@example.com>
    @license  GNU GPL v3 http://example.com/
    @link     http://example.com/
     */
    $x => 123;

**Comment by jrfnl** [comment] 2023-01-07 23:29
Duplicate of #3693, #3491, #2930

PHPCS is often used within IDEs during live coding, so, generally speaking, it will ignore parse errors.
Along the same lines, something which may be a parse error in one PHP version, may not be on another PHP version.

If you want parse errors to be reported, you can add the `Generic.PHP.Syntax` sniff to your ruleset, though be aware that it will report based on the PHP version used during the PHPCS scan.
Alternatively, use a dedicated linting tool like [PHP Parallel Lint](https://github.com/php-parallel-lint/PHP-Parallel-Lint/) or [PHPLint](https://github.com/overtrue/phplint).

**Closed** 2023-01-08 05:36 UTC
