### ISSUE TITLE
3.0.0 - Config file lookup continues despite a file has already been found

### ISSUE THREAD

**Issue by ndm2** [squizlabs/PHP_CodeSniffer#1455] opened 2017-05-07 20:55 UTC
When looking up config files, PHPCS always traverses the whole directory branch, starting from the current working directory, going up to the top level directory.

I'm not sure whether whether it's considered a bug or intentional, but I would have expected that the automatic lookup uses the closest config file that can be found, ie the first one it stumbles over on its way up to the top level directory, not the last one?

I just noticed it as PHPCS was trying to traverse into directories where PHP has no read/write permissions.

refs #626

**Comment by gsherwood** [comment] 2017-05-07 22:22
Thanks for reporting this. It is technically a behaviour change, but it's also not working as intended. The first file it finds was supposed to be used, so I'm treating this one as a bug because I don't think anyone would wont the functionality as it was committed.

**Closed by gsherwood** 2017-05-07 22:22 UTC
Labels: Bug
