### ISSUE TITLE
PHP Fatal error:  Class 'PHP_CodeSniffer_Exception' not found

### ISSUE THREAD

**Issue by jonnyijapan** [squizlabs/PHP_CodeSniffer#2421] opened 2019-02-13 01:18 UTC
I'm getting 

```
PHP Fatal error:  Class 'PHP_CodeSniffer_Exception' not found in ~/rules/FuelPHP/Sniffs/Classes/ClassDeclarationSniff.php on line 16
Could not open input file: Fatal
```

all of the time.

Using
PHP 7.1.23 (I also tried installing PHP 5.6 and execute with that but no good)
macOS mojave 10.14.3.

Command used is

`php ~/repos/PHP_CodeSniffer/bin/phpcs --report=json --standard="~/rules/FuelPHP/ruleset.xml" ~/repos/app/index.php`

First time user here so bare with me but what's wrong?

**Comment by jrfnl** [comment] 2019-02-13 01:38
Looks like the FuelPHP CS standard is not (yet) compatible with PHPCS 3.x.

You will need to downgrade to PHPCS 2.x to get it working or let Composer sort it out for you.

**Comment by gsherwood** [comment] 2019-02-13 02:09
Closing as I can confirm this is a FuelPHP CS issue. You'll need to use a 2.x version of PHPCS with this standard, or petition them to upgrade it.

**Closed by gsherwood** 2019-02-13 02:09 UTC

**Comment by jonnyijapan** [comment] 2019-02-13 02:31
Yes I just found it out also, working now with phpcs 2.9, sorry for the confusion. Thanks all
