### ISSUE TITLE
Consider "0 of 0 fixed" as success

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#408] opened 2014-12-28 22:27 UTC
Currently I see following output for file where nothing can be fixed:
```
Processing document_eh.php [PHP => 14 tokens in 5 lines]... DONE in 2ms (0 fixable violations)
	=> Fixing file: 0/0 violations remainingERROR in 0ms
```
I'd rather consider this case as `DONE` not as `ERROR`.

**Comment by gsherwood** [comment] 2015-01-05 02:48
This is actually a duplicate of #401 as both have the same issue. I'm closing this one as I've already asked for more info on the other one.

**Closed by gsherwood** 2015-01-05 02:48 UTC
