### ISSUE TITLE
Control Structures New Lines

### ISSUE THREAD

**Issue by dazzle-software** [squizlabs/PHP_CodeSniffer#1115] opened 2016-08-13 03:58 UTC
Hello is it possible to alter the class Squiz_Sniffs_ControlStructures_ControlSignatureSniff to allow new line rather then space.

as I not having much luck as not even sure how to debug your script being a command line tool as I been using phpstorm and that does not really help with debugging your code.

and using cmd in windows just seems to create so much which next to no sense using the verbose mode 

Stephen

**Comment by aik099** [comment] 2016-08-13 07:34
In other words you want this code

```php
if ( condition )
{
```

instead of this code

```php
if ( condition ) {
```

?

The `Squiz` standard wants code to look a specific way. In most cases if particular sniff isn't configurable, then it's not going to be changed. Other story is with sniffs from `Generic` standard, where almost every sniff have settings.

Maybe sniff from other standard would do what you need.

**Comment by gsherwood** [comment] 2016-08-14 21:43
You probably could change that sniff's code, but it makes so many assumptions about the layout of the control structures that you'd probably be better off rewriting it.

There are no included sniffs that enforce the coding style you want, so you'd have to look around for another PHPCS coding standard that does, or write your own sniff to do it.

I'll leave this open as a feature request. There would be some benefit to being able to use the function opening brace sniffs to check the brace placement of control structures as well.

**Comment by photodude** [comment] 2016-09-04 21:46
The in development Joomla Coding standard using PHPCS 2 has this kind of control structure brackets.

https://github.com/photodude/coding-standards/blob/phpcs-2/Joomla/Sniffs/ControlStructures/ControlStructuresBracketsSniff.php

(fyi there is a problem with the unit tests for sniff at the moment. I'm still trying to figure out what the issue is causing the unit tests for the sniff to fail).

**Comment by gsherwood** [comment] 2018-01-03 04:53
Closing as I've had no additional interest or PRs for this.

**Closed by gsherwood** 2018-01-03 04:53 UTC
Labels: Enhancement

**Comment by photodude** [comment] 2018-01-03 19:40
@gsherwood would you be interested in including the sniff for enforcing control structure brackets on new line? 
The code we are using is just a modified version of `PEAR.Classes.ClassDeclaration` Sniff using different tokens. I would assume it would be something that would go in the General standard. 
The sniff works great for enforcing the control structure brackets on new line, but the indenting of the brackets has a case where it fails to indent correctly (i.e. within closures)

**Comment by gsherwood** [comment] 2018-01-03 21:27
> would you be interested in including the sniff for enforcing control structure brackets on new line?

If you submit a PR, I'd certainly review it.
