### ISSUE TITLE
Ruleset hard-coded file paths are not used if not running from the same directory as the ruleset

### ISSUE THREAD

**Issue by gsouf** [squizlabs/PHP_CodeSniffer#822] opened 2015-12-15 08:58 UTC
When I run phpcs version  2.5.0 on my project the script never ends and so does phpcbf.
Either I run phpcs with custom arguments or simply with ``./vendor/bin/phpcs`` it will fail (never end)

Now if I downgrade to 2.4.0 it works well.

I'm afraid I can't give more useful information but feel free to ask for details.

UPDATE: It seems that php version does not matter (5.4 5.4 5.6 7.0)

**Comment by gsouf** [comment] 2015-12-15 09:34
Got it. It's due to file path from xml. It seems the behaviours changed since version 2.4.0. 
Creaitng a patch for that

**Comment by aik099** [comment] 2015-12-15 10:37
I'm not sure this is needed in 2.x versions because in 3.x versions this behavior is changed to immediately exit when no file contents is provided.

**Comment by gsouf** [comment] 2015-12-15 10:43
I found where the issue comes from.

This addition in the version 2.5: http://git.io/v0ghw  the ``<file>`` nodes are getting ignored if the xml file is not in the same directory as the cwd.

I use to store my ruleset.xml in an other directory, and then it broke my build. 

That's a compatibility break that should not occur in a minor version update. 

Did my part of the job, no it's up to you to tell if yes or not you want to go back to the previous behaviour. :)

**Comment by gsouf** [comment] 2015-12-15 10:44
@aik099  even if 3 changed, it's good to fix version 2 ! Isn't it ?

**Comment by aik099** [comment] 2015-12-15 12:03
> @aik099 even if v3 changed, it's good to fix version 2 ! Isn't it ?

Sure this needs to be fixed in 2.x versions.

**Comment by gsherwood** [comment] 2015-12-15 21:50
As you've figure out already, the problem is caused by PHPCS not processing hard-coded file paths unless the command is being run from the same directory as the ruleset. This was originally to allow PHPCS to find phpcs.xml files up the tree and use those for processing, but I obviously fixed the file path issue another way and didn't need that extra check in the end because the functionality still works without it.

Until a fix is released, you will need to specify the file paths in your build script. The rest of the ruleset should be processed normally.

**Comment by gsherwood** [comment] 2015-12-15 21:54
After further investigation, this code was from a fix for the 3.0 version and is not needed in 2.x because of a different way it merges CLI arguments and ruleset values. So looked safe to remove from 2.x after testing.

**Closed by gsherwood** 2015-12-15 21:54 UTC
Labels: Bug
