### ISSUE TITLE
PSR12.Files.ImportStatement with core php classes.

### ISSUE THREAD

**Issue by fr3nch13** [squizlabs/PHP_CodeSniffer#2710] opened 2019-11-19 21:33 UTC
New in 3.5.2 is now throwing the `PSR12.Files.ImportStatement` when importing a class from php's core using a leading `\`.

Example:
```php
// RuntimeException.php
<?php

/**
 * RuntimeException
 */

namespace My\NameSpace;

use \RuntimeException as BaseRuntimeException; // <-- Here. the 'use \RuntimeException' part.

/**
 * Runtime Exception
 *
 * Wrapper for the default Runtime Exception.
 */
class RuntimeException extends BaseRuntimeException
{
}

```

**Comment by michalbundyra** [comment] 2019-11-19 21:43
And it's correct. You can safely just drop leading `\` after use.
See: https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements

> Import statements MUST never begin with a leading backslash as they must always be fully qualified.

**Comment by fr3nch13** [comment] 2019-11-19 23:57
Makes sense actually. I just tested, and I didn't have any conflicts as long as you `use` your own properly:

```php
// RuntimeException.php
<?php

/**
 * RuntimeException
 */

namespace My\NameSpace;

use RuntimeException as BaseRuntimeException;

/**
 * Runtime Exception
 *
 * Wrapper for the default Runtime Exception.
 */
class RuntimeException extends BaseRuntimeException
{
}
```
```php
// ExtendedRuntimeException.php
<?php

/**
 * ExtendedRuntimeException
 */

namespace My\NameSpace;

use My\NameSpace\RuntimeException; // <!-- make sure you use the namespace path.

/**
 * Extended Runtime Exception
 *
 * Wrapper for the default Extended Runtime Exception.
 */
class ExtendedRuntimeException extends RuntimeException
{
}

**Comment by jrfnl** [comment] 2019-11-20 00:01
> use My\NameSpace\RuntimeException; // <!-- make sure you use the namespace path.

You can actually drop that `use` statement completely as you are importing a class from the same namespace, which is unnecessary.

**Comment by fr3nch13** [comment] 2019-11-20 00:24
Would it automatically assume your own defined RuntimeException or php's core RuntimeException?

**Comment by jrfnl** [comment] 2019-11-20 00:32
> Would it automatically assume your own defined RuntimeException or php's core RuntimeException?

Yes it would. See: https://www.php.net/manual/en/language.namespaces.rules.php

> If it will assume your defined RuntimeException over php's, then I would still keep the use for clarity.
That way other developers know you're using your own RuntimeExpection over php's core.

That's fair enough.

**Comment by gsherwood** [comment] 2019-11-20 01:45
Closing as the sniff is working as intended, but thanks to those who provided help with the explanation.

**Closed by gsherwood** 2019-11-20 01:45 UTC
