### ISSUE TITLE
PHPCBF fails to fix attached file

### ISSUE THREAD

**Issue by paulschreiber** [squizlabs/PHP_CodeSniffer#2091] opened 2018-07-12 03:00 UTC
With the attached [test.php.zip](https://github.com/squizlabs/PHP_CodeSniffer/files/2186908/test.php.zip) file (also shown here)

```php
<?php
class Item {

	public function foo() {
		?>
		<tr>
		</tr>
	<?php
	}

	public static function bar() {
		$bug_terms = apply_filters( 'abc', '', array( // @codingStandardsIgnoreLine
			'xyz' => true,
		) );

		return $bug_data;
	}

	public static function baz() {
		if ( true ) {
			return false;
		}
		?>
			<span>
			</span>
		<?php
	}
}
```

I get this output:
```
$ phpcbf --standard=WordPress-VIP  ~/Desktop/test.php 

PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
/Users/paul/Desktop/test.php                          FAILED TO FIX
----------------------------------------------------------------------
A TOTAL OF 1 ERROR WERE FIXED IN 1 FILE
----------------------------------------------------------------------
PHPCBF FAILED TO FIX 1 FILE
----------------------------------------------------------------------

Time: 204ms; Memory: 6Mb
```

Hopefully this reduced test case helps.

This is with PHP 7.1.16, phpcs 3.3.0 and macOS 10.13.6.

**Comment by paulschreiber** [comment] 2018-07-12 03:04
FYI the ignore message is there to prevent the `WordPress.NamingConventions.ValidHookName.UseUnderscores` error on `taxonomy-images-get-the-terms` (which should be `taxonomy_images_get_the_terms`).

**Comment by gsherwood** [comment] 2018-07-12 04:59
This can be replicated with the included Squiz standard using the following code:
```php
<?php
$foo = foo(array( // comment
) );
```
The problem looks to be caused by the comment placement during array fixing, but I need to look into it a bit more.

**Comment by gsherwood** [comment] 2018-07-12 05:49
There was a generic issue with the ArrayDeclaration sniff trying to turn multi-line arrays into single line arrays, but not being able to due to the comment being there (it would comment out the array contents if it did). I've fixed that, but that's not the specific problem here.

Code the produces the new problem is:
```php
$foo = foo([ // @codingStandardsIgnoreLine
]
);
```
The ArrayIndent sniff wants the close brace at column 0, but the multi-line function call sniff wants every line inside to be indented at least once.

This normally fixes itself because the first argument in a multi-line function call must be on the next line, so the array is moved down and the indent rules work fine:
```php
$foo = foo(
    [
    // ignore comment was here
    ]
```
But because you are ignoring all sniffs, that fixer doesn't get a chance to run.

I have not looked into seeing if I can fix this yet, but one solution (assuming you are on PHPCS v 3.2.0 or higher) is to specify a specific error code (or sniff) to disable instead of turning everything off:
```php
<?php
$bug_terms = apply_filters( 'abc', '', array( // phpcs:ignore WordPress.NamingConventions.ValidHookName.UseUnderscores
    'xyz' => true,
) );
```
WordPress has a different array indentation sniff, but I think it is having the exact same problem as the core one, and it looks to be conflicting with the multi-line function call sniff (`PEAR.Functions.FunctionCallSignature`) in the same way.

Assuming you can't use a more specific ignore comment, and I find a fix that allows the sniffs to stop conflicting in this case, I think the WordPress standard will need a fix applied to make this work.

**Comment by jrfnl** [comment] 2018-07-12 06:57
FWIW: The `WordPress.Arrays.ArrayIndentation` sniff is the only sniff in WPCS I haven't adjusted yet to deal correctly with the new ignore annotations. Still working on it.

**Comment by paulschreiber** [comment] 2018-07-12 12:21
In my case, I'm happy to use `phpcs:ignore WordPress.NamingConventions.ValidHookName.UseUnderscores`. I'll let you decide how you want to handle the rest of the issue.

This works:
```
$bug_terms = apply_filters( // phpcs:ignore WordPress.NamingConventions.ValidHookName.UseUnderscores
	'taxonomy-images-get-the-terms', '', array(
		'having_images' => true,
		'post_id'       => $post_id,
		'taxonomy'      => self::TAXONOMY_SLUG,
	)
);
```

This does not:
```
$bug_terms = apply_filters( 
	'taxonomy-images-get-the-terms', '', array( // phpcs:ignore WordPress.NamingConventions.ValidHookName.UseUnderscores
		'having_images' => true,
		'post_id'       => $post_id,
		'taxonomy'      => self::TAXONOMY_SLUG,
	)
);
```

Took me a minute to figure out where to put the ignore comment.

**Comment by jrfnl** [comment] 2018-07-12 21:50
@paulschreiber Just to let you know there are two more alternatives available to you (until I actually manage to fix that sniff):

1. This should also work for the fixers as well as ignoring the notice:
```php
$bug_terms = apply_filters( 
	// phpcs:ignore WordPress.NamingConventions.ValidHookName.UseUnderscores
	'taxonomy-images-get-the-terms', '', array(
		'having_images' => true,
		'post_id'       => $post_id,
		'taxonomy'      => self::TAXONOMY_SLUG,
	)
);
```

2. If the project you are working on uses a `dash` often in hook names and you use a custom ruleset, you can tell WPCS to allow for additional hook name delimiters. Have a look at the info about Customizable properties in the WPCS wiki](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#custom-word-delimiters-in-hook-names) to see how this works.

**Comment by paulschreiber** [comment] 2018-07-13 00:40
The dash comes from the [taxonomy-images](https://github.com/mfields/Taxonomy-Images) plugin. We use underscores in all of our own filters.

I just filed https://github.com/mfields/Taxonomy-Images/issues/34.

**Comment by gsherwood** [comment] 2018-10-11 05:43
I've had another think about this and I can't see how it can be fixed. I think the solution to use a more specific ignore comment might be the only one, so I'm going to close this. If it comes up again, I'll have another think.

**Closed by gsherwood** 2018-10-11 05:43 UTC
