### ISSUE TITLE
PHP Deprecated:  preg_match(): Passing null to parameter #2 

### ISSUE THREAD

**Issue by web-programmer-here** [squizlabs/PHP_CodeSniffer#3760] opened 2023-02-15 21:25 UTC
**Describe the bug**
When running the phpcs on a WordPress plugin, I get this error:

```
PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) 
of type string is deprecated in ../squizlabs/php_codesniffer/src/Config.php on line 228

Deprecated: preg_match(): Passing null to parameter #2 ($subject) 
of type string is deprecated in ../squizlabs/php_codesniffer/src/Config.php on line 228
....... 7 / 7 (100%)
```

**Expected behavior**
No error showing up

**Versions (please complete the following information):**
 - OS: MacOS
 - PHP: 8.2
 - PHP_CodeSniffer version 3.7.1 (stable) by Squiz (http://www.squiz.net)
 - Standard: WordPress

**Additional context**
```
stty --version
stty (GNU coreutils) 8.23
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by jrfnl** [comment] 2023-02-15 22:19
@web-programmer-here Thanks for creating the issue. Would you mind running `stty size` for me and posting the output ?

**Comment by web-programmer-here** [comment] 2023-02-15 23:05
@jrfnl , I get an error running that command
```
stty size
Abort trap: 6
```

**Comment by jrfnl** [comment] 2023-02-15 23:10
Ow, interesting. That definitely looks like the cause of the problem.

Could you try to run `stty --help` to see what it says ? I'd like to compare it with what I see locally (I have `stty` v 8.32)

**Comment by web-programmer-here** [comment] 2023-02-15 23:12
@jrfnl thanks for the quick reply, yes, here it is

```shell
stty --help
Usage: stty [-F DEVICE | --file=DEVICE] [SETTING]...
  or:  stty [-F DEVICE | --file=DEVICE] [-a|--all]
  or:  stty [-F DEVICE | --file=DEVICE] [-g|--save]
Print or change terminal characteristics.

Mandatory arguments to long options are mandatory for short options too.
  -a, --all          print all current settings in human-readable form
  -g, --save         print all current settings in a stty-readable form
  -F, --file=DEVICE  open and use the specified DEVICE instead of stdin
      --help     display this help and exit
      --version  output version information and exit

Optional - before SETTING indicates negation.  An * marks non-POSIX
settings.  The underlying system defines which settings are available.

Special characters:
 * dsusp CHAR    CHAR will send a terminal stop signal once input flushed
   eof CHAR      CHAR will send an end of file (terminate the input)
   eol CHAR      CHAR will end the line
 * eol2 CHAR     alternate CHAR for ending the line
   erase CHAR    CHAR will erase the last character typed
   intr CHAR     CHAR will send an interrupt signal
   kill CHAR     CHAR will erase the current line
 * lnext CHAR    CHAR will enter the next character quoted
   quit CHAR     CHAR will send a quit signal
 * rprnt CHAR    CHAR will redraw the current line
   start CHAR    CHAR will restart the output after stopping it
   stop CHAR     CHAR will stop the output
   susp CHAR     CHAR will send a terminal stop signal
 * swtch CHAR    CHAR will switch to a different shell layer
 * werase CHAR   CHAR will erase the last word typed

Special settings:
   N             set the input and output speeds to N bauds
 * cols N        tell the kernel that the terminal has N columns
 * columns N     same as cols N
   ispeed N      set the input speed to N
 * line N        use line discipline N
   min N         with -icanon, set N characters minimum for a completed read
   ospeed N      set the output speed to N
 * rows N        tell the kernel that the terminal has N rows
 * size          print the number of rows and columns according to the kernel
   speed         print the terminal speed
   time N        with -icanon, set read timeout of N tenths of a second

Control settings:
   [-]clocal     disable modem control signals
   [-]cread      allow input to be received
 * [-]crtscts    enable RTS/CTS handshaking
 * [-]cdtrdsr    enable DTR/DSR handshaking
   csN           set character size to N bits, N in [5..8]
   [-]cstopb     use two stop bits per character (one with '-')
   [-]hup        send a hangup signal when the last process closes the tty
   [-]hupcl      same as [-]hup
   [-]parenb     generate parity bit in output and expect parity bit in input
   [-]parodd     set odd parity (or even parity with '-')
 * [-]cmspar     use "stick" (mark/space) parity

Input settings:
   [-]brkint     breaks cause an interrupt signal
   [-]icrnl      translate carriage return to newline
   [-]ignbrk     ignore break characters
   [-]igncr      ignore carriage return
   [-]ignpar     ignore characters with parity errors
 * [-]imaxbel    beep and do not flush a full input buffer on a character
   [-]inlcr      translate newline to carriage return
   [-]inpck      enable input parity checking
   [-]istrip     clear high (8th) bit of input characters
 * [-]iutf8      assume input characters are UTF-8 encoded
 * [-]iuclc      translate uppercase characters to lowercase
 * [-]ixany      let any character restart output, not only start character
   [-]ixoff      enable sending of start/stop characters
   [-]ixon       enable XON/XOFF flow control
   [-]parmrk     mark parity errors (with a 255-0-character sequence)
   [-]tandem     same as [-]ixoff

Output settings:
 * bsN           backspace delay style, N in [0..1]
 * crN           carriage return delay style, N in [0..3]
 * ffN           form feed delay style, N in [0..1]
 * nlN           newline delay style, N in [0..1]
 * [-]ocrnl      translate carriage return to newline
 * [-]ofdel      use delete characters for fill instead of NUL characters
 * [-]ofill      use fill (padding) characters instead of timing for delays
 * [-]olcuc      translate lowercase characters to uppercase
 * [-]onlcr      translate newline to carriage return-newline
 * [-]onlret     newline performs a carriage return
 * [-]onocr      do not print carriage returns in the first column
   [-]opost      postprocess output
 * tabN          horizontal tab delay style, N in [0..3]
 * tabs          same as tab0
 * -tabs         same as tab3
 * vtN           vertical tab delay style, N in [0..1]

Local settings:
   [-]crterase   echo erase characters as backspace-space-backspace
 * crtkill       kill all line by obeying the echoprt and echoe settings
 * -crtkill      kill all line by obeying the echoctl and echok settings
 * [-]ctlecho    echo control characters in hat notation ('^c')
   [-]echo       echo input characters
 * [-]echoctl    same as [-]ctlecho
   [-]echoe      same as [-]crterase
   [-]echok      echo a newline after a kill character
 * [-]echoke     same as [-]crtkill
   [-]echonl     echo newline even if not echoing other characters
 * [-]echoprt    echo erased characters backward, between '\' and '/'
   [-]icanon     enable erase, kill, werase, and rprnt special characters
   [-]iexten     enable non-POSIX special characters
   [-]isig       enable interrupt, quit, and suspend special characters
   [-]noflsh     disable flushing after interrupt and quit special characters
 * [-]prterase   same as [-]echoprt
 * [-]tostop     stop background jobs that try to write to the terminal
 * [-]xcase      with icanon, escape with '\' for uppercase characters

Combination settings:
 * [-]LCASE      same as [-]lcase
   cbreak        same as -icanon
   -cbreak       same as icanon
   cooked        same as brkint ignpar istrip icrnl ixon opost isig
                 icanon, eof and eol characters to their default values
   -cooked       same as raw
   crt           same as echoe echoctl echoke
   dec           same as echoe echoctl echoke -ixany intr ^c erase 0177
                 kill ^u
 * [-]decctlq    same as [-]ixany
   ek            erase and kill characters to their default values
   evenp         same as parenb -parodd cs7
   -evenp        same as -parenb cs8
 * [-]lcase      same as xcase iuclc olcuc
   litout        same as -parenb -istrip -opost cs8
   -litout       same as parenb istrip opost cs7
   nl            same as -icrnl -onlcr
   -nl           same as icrnl -inlcr -igncr onlcr -ocrnl -onlret
   oddp          same as parenb parodd cs7
   -oddp         same as -parenb cs8
   [-]parity     same as [-]evenp
   pass8         same as -parenb -istrip cs8
   -pass8        same as parenb istrip cs7
   raw           same as -ignbrk -brkint -ignpar -parmrk -inpck -istrip
                 -inlcr -igncr -icrnl  -ixon  -ixoff  -iuclc  -ixany
                 -imaxbel -opost -isig -icanon -xcase min 1 time 0
   -raw          same as cooked
   sane          same as cread -ignbrk brkint -inlcr -igncr icrnl -iutf8
                 -ixoff -iuclc -ixany imaxbel opost -olcuc -ocrnl onlcr
                 -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
                 isig icanon iexten echo echoe echok -echonl -noflsh
                 -xcase -tostop -echoprt echoctl echoke, all special
                 characters to their default values

Handle the tty line connected to standard input.  Without arguments,
prints baud rate, line discipline, and deviations from stty sane.  In
settings, CHAR is taken literally, or coded as in ^c, 0x37, 0177 or
127; special values ^- or undef used to disable special characters.

GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
For complete documentation, run: info coreutils 'stty invocation'
```

**Comment by jrfnl** [comment] 2023-02-15 23:32
@web-programmer-here Looks like `size` (under "special settings") is available in your `stty` version, but blocked by your system ?

> An * marks non-POSIX settings.  The underlying system defines which settings are available.

While PHPCS, of course, shouldn't throw an error for that (and it will be fixed), the underlying cause does appear to be system configuration.

As I'm not on Mac, I honestly wouldn't know what to advise you.

If you know the size of your console, you could pass the `reportWidth` value on the CLI or set it in your config to get rid of the notice in the mean time.
```bash
# For an individual PHPCS run:
phpcs --report-width=100 ... # (whatever other CLI arguments you pass)

# For all PHPCS runs:
phpcs --config-set report_width 120
```

Also see: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-default-report-width

**Comment by web-programmer-here** [comment] 2023-02-23 04:28
@jrfnl I am not even sure what is `stty` haha never touched any settings related to this
I try to see if I can pass `reportWidth` like you mentioned. Thank you

**Comment by web-programmer-here** [comment] 2023-03-13 02:26
@jrfnl I tried updating the width but it did not work, I even increased it to 250

**Comment by jrfnl** [comment] 2023-03-13 05:37
@web-programmer-here Hmm... well, I opened PR #3761 to get rid of the error. Would be great if you could test to see if that works for you ?

**Closed** 2023-05-07 04:46 UTC
Labels: Type: bug, Core Component: Config & Ruleset & CLI options

**Comment by jrfnl** [comment] 2023-12-08 23:55
FYI: the fix for this issue is included in today's [PHP_CodeSniffer 3.8.0 release](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0).

As per #3932, development on PHP_CodeSniffer will continue in the [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer) repository. If you want to stay informed, you may want to start "watching" that repo (or watching releases from that repo).
