### ISSUE TITLE
False-positive for consts

### ISSUE THREAD

**Issue by leocavalcante** [squizlabs/PHP_CodeSniffer#2634] opened 2019-10-02 22:31 UTC
`Visibility must be declared on all constants if your project supports PHP 7.1 or later`

But the const is on the file root-level, not inside a class.

**Comment by gsherwood** [comment] 2019-10-02 22:34
Duplicate of #2615, which is fixed in master and will be release in 3.5.1

**Closed by gsherwood** 2019-10-02 22:34 UTC
