### ISSUE TITLE
LowercasePHPFunctions sniff failing on "new \File()"

### ISSUE THREAD

**Issue by josephzidell** [squizlabs/PHP_CodeSniffer#2452] opened 2019-03-21 04:31 UTC
I've got a class `File` in the global namespace, and with the latest update, PHPCS is showing this false positive:

```
Calls to PHP native functions must be lowercase; expected "file" but found "File"
```

Code:
```php
$filePath = new \File($path);
```

**Comment by gsherwood** [comment] 2019-03-21 04:46
Looks to be caused by #2252 but is a quick fix

**Comment by gsherwood** [comment] 2019-03-21 04:50
Fix will be in 3.4.2, which I'll be trying to release next week

**Comment by gsherwood** [comment] 2019-03-21 04:50
Thanks a lot for reporting this

**Closed by gsherwood** 2019-03-21 04:50 UTC
Labels: Bug

**Comment by josephzidell** [comment] 2019-03-21 05:04
Thanks for the quick response and fix!
