### ISSUE TITLE
Incorrect scope matching when arrow function used inside IF condition

### ISSUE THREAD

**Issue by snapshotpl** [squizlabs/PHP_CodeSniffer#2867] opened 2020-02-12 12:43 UTC
I run phpcs with slevomat/coding-standard and I get error:

```
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_closer in /var/www/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 195 in /var/www/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 /var/www/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(195): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined index...', '/var/www/vendor...', 195, Array)
#1 /var/www/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(137): SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers(Object(PHP_CodeSniffer\Files\LocalFile), 0)
#2 /var/www/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Namespaces/UselessAliasSniff.php(40): SlevomatCodingStandard\Helpers\UseStatementHelper::getFileUseStatements(Object(PHP_CodeSniffer\Files\LocalFile))
#3 /var/www/vendor/squizlabs/php_codesniffer/src/Files/File.php(496): SlevomatCodingStandard\Sniffs\Names in /var/www/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
```

This is code which causes error:

```php
<?php

class MyClass
{
    public function __construct() {
        if (
            $this->valid(fn(): bool => 2 > 1)
        ) {

        }
    }

    private function valid(callable $callable): bool
    {
        return $callable();
    }
}
```

First reported here https://github.com/slevomat/coding-standard/issues/902

**Comment by kukulich** [comment] 2020-02-12 12:47
I was able to prepare a workaround but I suppose that `T_CLASS` token should have `scope_opener` and `scope_closer`.

https://github.com/slevomat/coding-standard/commit/4c88f6c3d81d189bf2f4dfb0946f145d816a2048

**Comment by jrfnl** [comment] 2020-02-12 14:17
Confirmed. But there's more going on here: the `T_COLON` for the return type of the `fn` arrow function within the `if` condition is being seen as the scope opener for the `if`.

I have a feeling that's what's throwing everything off.

The check for scope openers for control structures using alternative syntax should probably make sure that the close parenthesis of the control structure's open parenthesis has been seen _before_ looking for a scope opener.

**Comment by gsherwood** [comment] 2020-03-16 22:31
I think this is going to require the arrow function detection code to be moved out of processAdditional and into the main process method.

**Comment by gsherwood** [comment] 2020-03-24 23:04
> I think this is going to require the arrow function detection code to be moved out of processAdditional and into the main process method.

Much much easier said than done. Probably need to figure something else out.

**Comment by gsherwood** [comment] 2020-03-25 22:27
Looks like it's easier to just ensure that a scope opener has the same nested parenthesis as the scope condition. So in this case, the T_COLON is nested differently to the T_IF, so it can't be the scope opener for it.

**Comment by gsherwood** [comment] 2020-03-25 23:41
I've pushed up a fix for this issue and PHPCS is now matching the scope openers and closers correctly for the code sample. If you get a chance to test, please let me know if there are other code snippets where this doesn't work. Thanks for the report.

**Closed by gsherwood** 2020-03-25 23:41 UTC
Labels: Bug
