### ISSUE TITLE
Expected type hint "MyClass[]"; found "array"

### ISSUE THREAD

**Issue by NikolaySl** [squizlabs/PHP_CodeSniffer#624] opened 2015-06-18 15:09 UTC
**Example code:**
```php
    /**
     * Does foo with MyClass objects.
     *
     * @param MyClass[] $list List of objects.
     */
    function foo( array $list ) {}
```

**Expected result:**
This should be OK.

**Actual result:**
```
 4 | ERROR | Expected type hint "MyClass[]"; found "array" for $list
```

**Comment by gsherwood** [comment] 2015-09-21 06:02
Duplicate of #601.

**Closed by gsherwood** 2015-09-21 06:03 UTC

**Comment by 6d70** [comment] 2025-03-10 09:52
Why was this closed? The comments in #601 clearly mentioned to create a new issue? 

I have the same issue, PHPStan is happy this comments but this rule is conflicting. What should the advice be when we PHPCS and PHPStan?
