### ISSUE TITLE
Generic ScopeIndent is confused by an short syntax array in case

### ISSUE THREAD

**Issue by VasekPurchart** [squizlabs/PHP_CodeSniffer#795] opened 2015-11-29 20:11 UTC
This produces errors consistently in both `PSR2` and `Squiz`:
```php
<?php

switch ($test) {
    case 'foo':
        return [
            1,
            2,
        ];
    case 'bar':
        return [
            1,
            2,
        ];
    default:
        throw new \Exception('Unexpected type');
}
```
errors from `PSR2`:
```
  9 | ERROR | [x] Line indented incorrectly; expected 8 spaces, found
    |       |     4 (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
 14 | ERROR | [x] Line indented incorrectly; expected 8 spaces, found
    |       |     4 (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
```

With `array()` this works fine, I've also tried combining with function calls, constructors etc. and narrowed it down to using the short array syntax. Probably not considered somewhere as scope opener/closer/both.

**Comment by gsherwood** [comment] 2015-11-29 22:08
This is a duplicate of #786 , which has been fixed in master.

**Closed by gsherwood** 2015-11-29 22:08 UTC

**Comment by VasekPurchart** [comment] 2015-11-29 22:12
Oh, sorry, thanks for pointing me to this. I checked only opened issues before submitting :(

**Comment by gsherwood** [comment] 2015-11-29 22:15
No problem at all. Better to report it again than not report it at all.
