### ISSUE TITLE
No Parentheses + Try / Catch

### ISSUE THREAD

**Issue by danielmedani** [squizlabs/PHP_CodeSniffer#1487] opened 2017-05-25 18:23 UTC
Weird but valid syntax to being with, a try catch within a non-parenthetical if statement will be transformed into an invalid statement.

Before (valid):
if (true)
    try {
        return true;
    } catch (Exception $e) {}

After (invalid):
if (true) {
    try {
        return true;
    }
} catch (Exception $e) {
}

**Comment by jrfnl** [comment] 2017-05-25 19:30
Duplicate of #1477 ?

**Comment by danielmedani** [comment] 2017-05-26 00:28
Looks like it!

**Comment by danielmedani** [comment] 2017-05-30 20:55
Ps... this causes a syntax error!

**Comment by jrfnl** [comment] 2017-06-18 02:04
What version of PHPCS are you using ? Please check with `phpcs --version`.
I cannot currently reproduce the issue. It looks like this was already fixed in January - see: #1253.

**Comment by gsherwood** [comment] 2017-07-04 06:26
Finally got around to testing this. Using 3.0.0RC2, I get this diff using the PSR2 standard:
```diff
 <?php
-if (true)
-try {
-return true;
-} catch (Exception $e) {}
+if (true) {
+    try {
+        return true;
+    }
+} catch (Exception $e) {
+}
```
Using the latest 3.0.1 release, I get this diff:
```diff
  <?php
-if (true)
-try {
-return true;
-} catch (Exception $e) {}
+if (true) {
+    try {
+        return true;
+    } catch (Exception $e) {
+    }
+}
```
So I can confirm it was a bug, but was fixed in RC3 and has been released. Can you test the latest version to see if it is working for you?

**Closed** 2017-12-08 09:09 UTC
Labels: Awaiting Feedback

**Comment by danielmedani** [comment] 2017-12-08 18:44
Sorry - missed this message.

I can not longer easily test... but glad to know that this has been fixed. Cheers
