### ISSUE TITLE
Wrong 'Code after EXIT statement cannot be executed' when using Switch-Case

### ISSUE THREAD

**Issue by Hoto-Cocoa** [squizlabs/PHP_CodeSniffer#1765] opened 2017-11-30 07:05 UTC
![image](https://user-images.githubusercontent.com/21969938/33417829-5ef796a4-d5e6-11e7-9f57-bb2c94396501.png)
![image](https://user-images.githubusercontent.com/21969938/33417847-6d8c5fce-d5e6-11e7-816a-2f2e440a3b54.png)
![image](https://user-images.githubusercontent.com/21969938/33418243-5074c8f2-d5e8-11e7-82cb-fe119608f8df.png)

This happens when make multiple array values with multiple lines.
If make array values in one line, this problem will not happen.

**Comment by jrfnl** [comment] 2017-11-30 07:59
I cannot reproduce the issue anymore on the current `master` branch.
Looks like this issue (accidentally) got fixed in commit https://github.com/squizlabs/PHP_CodeSniffer/commit/65ef0538ae2a65a6578eca550cc6aad64aaea901 which relates to #1590

**Comment by gsherwood** [comment] 2017-11-30 22:23
Yes, please try the latest master if you can. This looks like a problem caused by not using braces for your IF statement, which should be resolved in master.

**Closed** 2017-12-08 09:14 UTC
Labels: Awaiting Feedback
