### ISSUE TITLE
Request for first member var exception on Squiz.WhiteSpace.MemberVarSpacing

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#920] opened 2016-03-14 16:38 UTC
Squiz.WhiteSpace.MemberVarSpacing currently enforces a new line before all the member Vars including the first member var. It would be helpful (and would help avoid unnecessary custom sniffs), if there was an option to allow for an exception to the newline requirement on the first member var.

**Comment by glen-84** [comment] 2016-03-14 18:08
#725 ?

**Comment by gsherwood** [comment] 2016-05-09 23:20
Closing as a duplicate of #725

**Closed by gsherwood** 2016-05-09 23:20 UTC
