### ISSUE TITLE
EOL PHP 5.4 and 5.5?

### ISSUE THREAD

**Issue by truls1502** [squizlabs/PHP_CodeSniffer#2169] opened 2018-09-27 08:17 UTC
I was wondering, do you want me to create a PR to remove PHP 5.4 and 5.5 since they are EOL (End of Life) or are you keeping these PHP versions for any reason?

EOL of the versions are stated on http://php.net/supported-versions.php

**Comment by jrfnl** [comment] 2018-09-27 10:57
Duplicate of https://github.com/squizlabs/PHP_CodeSniffer/issues/1244

For PHPCS 3.x the answer will be "no".
See: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0a1

Not sure what the minimum PHP will be for [PHPCS 4.x](https://github.com/squizlabs/PHP_CodeSniffer/milestone/11), but development on that hasn't started yet AFAIK.

Oh and PHP 5.6 and 7.0 will be EOL within a few months a well :wink:

**Comment by Majkl578** [comment] 2018-09-27 11:42
@jrfnl That reasoning is over 2 years old.

Bumping PHP versions in minor releases is not a BC break, so it's a huge :+1: from me. Should be bumped to `^7.1` directly for PHPCS 3.4.

**Comment by gsherwood** [comment] 2018-09-27 22:59
> That reasoning is over 2 years old.

It still stands. I wont be reviewing the version requirements until version 4.

> Bumping PHP versions in minor releases is not a BC break

A minor version upgrade that stops the product working for anyone using an older PHP version feels like one of the biggest BC breaks I could possible do. I did this for HHVM because I knew I couldn't support HHVM going forward and I wasn't going to be releasing version 4 soon enough to break BC for it. But it's not like I'm going to find maintaining support for older PHP versions hard, so I'm not going to even consider dropping support for them until version 4.

Also note that I haven't even started work on version 4, so I'll be supporting the PHP versions I've committed to for quite some time.

**Closed by gsherwood** 2018-09-27 22:59 UTC

**Comment by Majkl578** [comment] 2018-09-28 02:09
> A minor version upgrade that stops the product working for anyone using an older PHP version feels like one of the biggest BC breaks I could possible do.

No. Minor versions are feature releases. Legacy users stay on legacy pach versions.
This topic has been discussed many times already, no need to repeat here. Please read the [Doctrine article about bumping PHP requirement](https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html). :)

> so I'll be supporting the PHP versions I've committed to for quite some time.

Two words only: _have fun_ (or _good luck_?).

**Comment by truls1502** [comment] 2018-09-28 08:32
Interested what it is written on [Doctrine article about bumping PHP requirement](https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html) - _Why dropping PHP support in a minor version is not a BC break_ section.
Copied the section part:
> # Why dropping PHP support in a minor version is not a BC break
> One question we frequently hear is, "isn't dropping support for a PHP version a BC break"? In a nutshell, no. A BC break happens when there is an incompatible change that your package manager can't handle. For example, changing a method signature in a minor version is a no-go, since the composer version constraints mentioned above assume any minor upgrade can safely be used.
> However, when we drop support for an older version of PHP, composer will not consider the new version if the PHP version requirement is no longer fulfilled. Thus, you won't end up with a fatal error due to a wrong method signature, you just won't get the new version.

Of course, you decide what you want to do. I just was asking if you need help regarding remove the PHP versions, I am happy to help you :)

**Comment by jrfnl** [comment] 2018-09-28 09:29
> A BC break happens when there is an incompatible change that your package manager can't handle. 

This presumes that everyone uses a package manager to manage PHPCS, but as - just like PHPUnit and numerous other tools - PHPCS is basic dev tooling, there are plenty of people who use the PHAR, the PEAR version or a git clone instead. Or use versions which might be shipped with their IDE or CI manager over which they may have little to no control.

So, the reasoning Doctrine uses, while valid in their use-case, does not necessarily apply to PHPCS.

**Comment by truls1502** [comment] 2018-09-28 09:35
Ok, @jrfnl - Thank you for the explanation :)

**Comment by vladyslavstartsev** [comment] 2020-03-05 21:07
@gsherwood @jrfnl 

you can officially support or just mention, that you can use https://github.com/cytopia/docker-phpcs this way you can do this ( drop EOL PHP support)

**Comment by jrfnl** [comment] 2020-03-06 05:44
@vladyslavstartsev I'm not sure I understand your point. The current minimum PHP version does not inhibit installing PHPCS on higher PHP versions. PHPCS runs fine on PHP 7.4 for that matter.

The docker image you mention above is just one way you can use to run PHPCS, but completely ignores all the other install methods which are currently still supported.

If it's about external standards: there's nothing stopping an external standard from setting a minimum PHP version which is higher than the minimum PHP version supported by PHPCS.

FYI: A look at the initial commits for PHPCS 4.x shows that the minimum version for that will be PHP 7.0, but this may still change.

**Comment by BafS** [comment] 2022-10-18 13:01
Is there any plan to release the version 4? The issue is over 4 years old.

Composer, which is also a dev tool, has bumped the minimum PHP version from 5.3 to 7.2 in a minor version ([v2.3.0](https://github.com/composer/composer/releases/tag/2.3.0)).

Looking at PHP statistics (https://packagist.org/php-statistics), the version 5.4 has 0% usage and was EOL 7 years ago (!), why not bumping the PHP version to have a more modern codebase with an almost non-existent impact on users? PHP 7.1 would cover almost 99% of the users for example.

**Comment by jrfnl** [comment] 2022-10-18 13:10
I have no idea about the timeline/planning for version 4, but I do know that the minimum PHP version will be bumped for 4.
At this time, it is set to be PHP 7.2, which you can see when looking at the 4.x branch.
