### ISSUE TITLE
Custom error messages don't have data replaced when cache is enabled

### ISSUE THREAD

**Issue by ncou** [squizlabs/PHP_CodeSniffer#2575] opened 2019-08-03 04:47 UTC
Hi,

The following sniff doesn't seems to work

https://github.com/slevomat/coding-standard/blob/master/build/phpcs-consistence.xml#L202
```
<rule ref="Squiz.Commenting.FunctionComment.MissingParamTag">
	<message>@param annotation for parameter "%s" missing</message>
</rule>
```
The %s string is not replaced with the parameter name. If i remove the custom message it works fine. Is it a regression ? or custom message doesn't support args ?

Thanks for your help.

**Comment by jrfnl** [comment] 2019-08-04 20:41
@ncou I'm not sure I understand the question. This works perfectly well in my experience.

Just to be sure I ran some tests and found no problems.

This is the code I used for the tests:
```php
<?php

/**
 * Test
 * @return void
 */
function test( $paramA, $paramB ) {
	return;
}
```

Initial ruleset:
```xml
<?xml version="1.0"?>
<ruleset name="Test-2575">
	<rule ref="Squiz.Commenting.FunctionComment.MissingParamTag"/>
</ruleset>
```

Result:
```
FILE: /phpcs-2575/test.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | Doc comment for parameter "$paramA" missing
 3 | ERROR | Doc comment for parameter "$paramB" missing
----------------------------------------------------------------------
```

Ruleset based on your described issue:
```xml
<?xml version="1.0"?>
<ruleset name="Test-2575">
	<rule ref="Squiz.Commenting.FunctionComment.MissingParamTag">
		<message>@param annotation for parameter "%s" missing</message>
	</rule>
</ruleset>
```

Result:
```
FILE: /phpcs-2575/test.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | @param annotation for parameter "$paramA" missing
 3 | ERROR | @param annotation for parameter "$paramB" missing
----------------------------------------------------------------------
```

**Comment by ncou** [comment] 2019-08-04 22:28
here is what i get when i run the test in local (using OS Windows 7 64bits).

```xml
<?xml version="1.0"?>
<ruleset name="Coding-Standard">
    <rule ref="Squiz.Commenting.FunctionComment.MissingParamTag">
        <message>@param annotation for parameter "%s" missing</message>
    </rule>
</ruleset>
```

Class :

```php
<?php

class Test
{
    /**
     * Test
     *
     * @return void
     */
    public function test($paramA, $paramB): void
    {
        echo 'test';
    }
}
```

Result :

```
FILE: src\Test.php
--------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------
LINE 5: ERROR @param annotation for parameter "%s" missing (Squiz.Commenting.FunctionComment.MissingParamTag)
LINE 5: ERROR @param annotation for parameter "%s" missing (Squiz.Commenting.FunctionComment.MissingParamTag)
--------------------------------------------------------------------------------------------------------------
   3:  class Test
   4:  {
>> 5:      /**
   6:       * Test
   7:       *
--------------------------------------------------------------------------------------------------------------
Time: 111ms; Memory: 4MB
```

**Comment by ncou** [comment] 2019-08-04 22:33
in my installed.json file it's indicated the php code sniffer version is 3.4.2.

**Comment by jrfnl** [comment] 2019-08-04 23:27
@ncou How are you running PHPCS ? How is PHPCS installed ?

I honestly cannot reproduce your issue, no matter what I try (and I'm on Windows 7 too).

**Comment by gsherwood** [comment] 2019-08-05 06:35
I can replicate this. It's a problem with caching. When re-adding the messages after loading from cache, the data isn't being replaced. I still need to look into where the problem is coming from.

If you use `--no-cache` you should see the correct error message, if you are experiencing the same problem.

**Comment by gsherwood** [comment] 2019-08-05 06:39
Actually, I know exactly what is happening.

When errors are replayed after loading from cache, LocalFile::replayErrors() calls File::addMessage() to put the error data back into the file without actually checking it. The addMessage() method looks at the ruleset and finds a custom message format using %s, so it overrides the message with the one from the ruleset. But it doesn't have any data to replace (it is only replaying the errors, not supplying any data) and so the %s goes unreplaced.

The solution for this is to allow addMessage to know that error are being replayed and to not go looking for ruleset settings for the message format.

**Comment by gsherwood** [comment] 2019-08-05 06:49
I've committed a fix for this, which will be in 3.5.0. For now, disabling cache is the only way to work around this. Or remove the custom error message from the ruleset until the fix is released.

**Closed by gsherwood** 2019-08-05 06:49 UTC
Labels: Bug

**Comment by ncou** [comment] 2019-08-05 17:09
Yes you are right, if i remove the line `<arg name="cache" value=".phpcs-cache"/>` in my phpcs.xml file the %s is replaced with the parameter value.

1) When do you think the v3.5.0 will be released ?

2) I was searching for a sniff to enforce the PSR Naming rule (interface file should have Interface suffix, idem for Trait and for Abstract class the prefix Abstract) but i could'nt find it in your package. Is there such a sniff in you package ? [sorry for using this issue for a question :-)]

**Comment by gsherwood** [comment] 2019-08-05 22:06
> 1. When do you think the v3.5.0 will be released ?

I really don't know. There is a very big refactoring project going into that release so it wont be out until that is complete.

> 2. I was searching for a sniff to enforce the PSR Naming rule (interface file should have Interface suffix, idem for Trait and for Abstract class the prefix Abstract) but i could'nt find it in your package. Is there such a sniff in you package ?

No, there is no included sniff for this as it isn't part of the PSR1/2/12 standards directly.

**Comment by ncou** [comment] 2019-08-06 05:34
Thank you for your answers. I will disable the cache and wait for the v3.5 :)
Keep up the good work.
